import React from 'react';
import { db } from '../../Config/firebase';
import { IBeneficiary, iBeneficiaryConverter } from '../../Models/Beneficiary.interface';
import { iClassroomConverter } from '../../Models/Classroom.interface';
import { dbKey } from '../../Models/databaseKeys';

const roomsToFix = [
  {
    city: 'Santa María',
    idcalOld: '1',
    dataInstance: '2016/03/04',
    dir: 'Biblioteca Municipal Gabriela Mistral, Av Irrarazabal S/N',
    colaborator: 'Municipalidad de Santa María',
    uuid: 'LcwPLxOXP9Y9e3FewiZD',
    idcal: 'R001',
  },
  {
    city: 'La Calera',
    idcalOld: '2',
    dataInstance: '2016/03/09',
    dir: 'Marathon N°312,La Calera',
    colaborator: 'Municipalidad de La Calera',
    uuid: 'ZoS5kUn20lmbKQzYIQBu',
    idcal: 'R002',
  },
  {
    city: 'Hijuelas',
    idcalOld: '4',
    dataInstance: '2016/03/16',
    dir: 'Casino Municipal, Manuel Rodriguez, N°1665',
    colaborator: 'Municipalidad de Hijuelas',
    uuid: 'BFjFdbOtjFbykanudML9',
    idcal: 'R004',
  },
  {
    city: 'Algarrobo',
    idcalOld: '6',
    dataInstance: '2016/03/22',
    dir: 'Sede Unión Juntas de Vecino UNCO, Av. Los Claveles Esquina Pescadores Poniente',
    colaborator: 'Municipalidad de Algarrobo',
    uuid: 'zk1nqtBsE6Wm6b91CIzu',
    idcal: 'R006',
  },
  {
    city: 'San Antonio',
    idcalOld: '8',
    dataInstance: '2016/03/29',
    dir: 'Gimnasio Liceo Juan Dante, Av. Barros Luco 2401, Barrancas',
    colaborator: 'Municipalidad de San Antonio',
    uuid: 'RKQTLnrlzqaU2MOsrbIN',
    idcal: 'R008',
  },
  {
    city: 'Santo Domingo',
    idcalOld: '9',
    dataInstance: '2016/03/30',
    dir: 'Salón Municipal, Plaza del Cabildo sn',
    colaborator: 'Municipalidad de Santo Domingo',
    uuid: 'rRQAKuP6NKGBlR6Z1Hry',
    idcal: 'R009',
  },
  {
    city: 'Llayllay',
    idcalOld: '7',
    dataInstance: '2016/03/31',
    dir: 'Teatro Municipal de Llay-llay Manuel Rodríguez sn',
    colaborator: 'Municipalidad de Llay llay',
    uuid: 'Pn0QyvpNmYk238cPymnp',
    idcal: 'R007',
  },
  {
    city: 'El Quisco',
    idcalOld: '12',
    dataInstance: '2016/04/07',
    dir: 'Auditorio Municipal, Av. Francia #066',
    colaborator: 'Municipalidad de El Quisco',
    uuid: '2axqPSFJUxvaqKobe0qa',
    idcal: 'R012',
  },
  {
    city: 'Hijuelas',
    idcalOld: '46',
    dataInstance: '2016/04/11',
    dir: 'Club Deportivo Los Pinos, Romeral',
    colaborator: 'Municipalidad de Hijuelas',
    uuid: 'F17G7vw79YcxJisy5liY',
    idcal: 'R046',
  },
  {
    city: 'Putaendo',
    idcalOld: '16',
    dataInstance: '2016/04/19',
    dir: 'Centro de Organizaciones Sociales, Camus N°277',
    colaborator: 'Municipalidad de Putaendo',
    uuid: 'LJlc1oTjSixjKASbuavP',
    idcal: 'R016',
  },
  {
    city: 'Panquehue',
    idcalOld: '18',
    dataInstance: '2016/04/26',
    dir: 'Población Héroes de la Concepción, Sector La Pirca',
    colaborator: 'Municipalidad de Panquehue',
    uuid: 'D3QgRNNVEXfzSnWN1NeJ',
    idcal: 'R018',
  },
  {
    city: 'Cabildo',
    idcalOld: '3',
    dataInstance: '2016/04/27',
    dir: 'Teatro Municipal de Cabildo, Calle Lautaro s/n',
    colaborator: 'Municipalidad de Cabildo',
    uuid: 'SCdgUWihzoqMwlGOg6Qu',
    idcal: 'R003',
  },
  {
    city: 'Catemu',
    idcalOld: '13',
    dataInstance: '2016/05/04',
    dir: 'Biblioteca Municipal, Borja García Huidobro N°025',
    colaborator: 'Municipalidad de Catemu',
    uuid: 'jRjGdjG7hTUhVEeqWr3b',
    idcal: 'R013',
  },
  {
    city: 'Quillota',
    idcalOld: '22',
    dataInstance: '2016/05/05',
    dir: 'Gimnasio del Adulto Mayor, Calle Merced N°145',
    colaborator: 'Municipalidad de Quillota',
    uuid: 'YYKvc0mOkyGiWZgJkDO9',
    idcal: 'R022',
  },
  {
    city: 'San Esteban',
    idcalOld: '17',
    dataInstance: '2016/05/09',
    dir: 'Salón Municipal, Av. 26 de Diciembre N°654',
    colaborator: 'Municipalidad de San Esteban',
    uuid: 'OdM8t5lcafoJ6Xky1GzK',
    idcal: 'R017',
  },
  {
    city: 'Cartagena',
    idcalOld: '23',
    dataInstance: '2016/05/10',
    dir: 'Liceo Poeta Vicente Huidobro, Avenida Casanova N° 660',
    colaborator: 'Municipalidad de Cartagena',
    uuid: 's8VwwcSB0y3DVimhNq2m',
    idcal: 'R023',
  },
  {
    city: 'Papudo',
    idcalOld: '25',
    dataInstance: '2016/05/12',
    dir: 'Villa Marina, calle El Coral s/n,',
    colaborator: 'Municipalidad de Papudo',
    uuid: 'CXJzEPNqGnt7sSmUzGwM',
    idcal: 'R025',
  },
  {
    city: 'Petorca',
    idcalOld: '15',
    dataInstance: '2016/05/13',
    dir: 'Salón Cultural Pte. Manuel Montt, Calle Silva Esquina Prat S/N Petorca',
    colaborator: 'Municipalidad de Petorca',
    uuid: 'V4eVz7VIwcJ5pirDLdEq',
    idcal: 'R015',
  },
  {
    city: 'La Ligua',
    idcalOld: '26',
    dataInstance: '2016/05/17',
    dir: 'Centro Cívico de la Ligua, Calle Pedro Polanco s/n Ex- Recinto Estación',
    colaborator: 'Municipalidad de La Ligua',
    uuid: 'M2zuR7W9eZUZXMYeNN6U',
    idcal: 'R026',
  },
  {
    city: 'El Tabo',
    idcalOld: '24',
    dataInstance: '2016/05/23',
    dir: 'Casa de la Cultura, Poeta Jonas N°85',
    colaborator: 'Municipalidad de El Tabo',
    uuid: '1aQUXzcMZxR8zIR5lS17',
    idcal: 'R024',
  },
  {
    city: 'Olmué',
    idcalOld: '28',
    dataInstance: '2016/05/24',
    dir: 'Salón Municipal, Prat N°12',
    colaborator: 'Municipalidad de Olmué',
    uuid: 'dJiB0myn6DPUZfjnCGia',
    idcal: 'R028',
  },
  {
    city: 'Los Andes',
    idcalOld: '20',
    dataInstance: '2016/05/26',
    dir: 'Centro cultural de Los Andes, Maipu N°475',
    colaborator: 'Municipalidad de Los Andes',
    uuid: 'WntR1wyGZrSolqxVy6sm',
    idcal: 'R020',
  },
  {
    city: 'La Calera',
    idcalOld: '14',
    dataInstance: '2016/06/01',
    dir: 'Salón municipal, Marathon N°312',
    colaborator: 'Municipalidad de La Calera',
    uuid: 'DXGUOW5OGzxl2f2GyYRW',
    idcal: 'R014',
  },
  {
    city: 'Casablanca',
    idcalOld: '34',
    dataInstance: '2016/06/08',
    dir: 'Teatro Municipal, Avenida Portales N°2',
    colaborator: 'Municipalidad de Casablanca',
    uuid: 'BVFKCJWgXRVwMeaYxmX2',
    idcal: 'R034',
  },
  {
    city: 'Rinconada',
    idcalOld: '35',
    dataInstance: '2016/06/09',
    dir: 'Salón Municipal,San Martín #607',
    colaborator: 'Municipalidad de Rinconada',
    uuid: 'Kb7vwNJYtmSZ18RypccM',
    idcal: 'R035',
  },
  {
    city: 'Valparaíso',
    idcalOld: '36',
    dataInstance: '2016/06/14',
    dir: 'Salón de Honor Municipal, Condell 1490',
    colaborator: 'Municipalidad de Valparaíso',
    uuid: 'S5qHD6pWm3B4ovb6o3u4',
    idcal: 'R036',
  },
  {
    city: 'Zapallar',
    idcalOld: '11',
    dataInstance: '2016/06/15',
    dir: 'Gimnasio Municipal de Catapilco, Balmaceda 381',
    colaborator: 'Municipalidad de Zapallar',
    uuid: '4DdGfJChsTDvUJnDfWVo',
    idcal: 'R011',
  },
  {
    city: 'Valparaíso',
    idcalOld: '37',
    dataInstance: '2016/06/16',
    dir: 'Salón de Honor Municipal, Condell 1490',
    colaborator: 'Municipalidad de Valparaíso',
    uuid: 'XEoPjuRkFTD8EXmKmsCq',
    idcal: 'R037',
  },
  {
    city: 'Valparaíso',
    idcalOld: '50',
    dataInstance: '2016/06/16',
    dir: 'Caleta Portales',
    colaborator: 'Municipalidad de Valparaíso',
    uuid: 'JwKisHclj814rW6zuvY3',
    idcal: 'R050',
  },
  {
    city: 'Valparaíso',
    idcalOld: '38',
    dataInstance: '2016/06/21',
    dir: 'Colegio Juan de Saavedra, Cerro Lecheros',
    colaborator: 'Municipalidad de Valparaíso',
    uuid: 'vrFUXTkvkD7F2APrsJdg',
    idcal: 'R038',
  },
  {
    city: 'Concón',
    idcalOld: '5',
    dataInstance: '2016/06/22',
    dir: 'Liceo Politécnico, Porvenir N°865',
    colaborator: 'Municipalidad de Concón',
    uuid: 'KbNExVOtC8fHbz3bjNdY',
    idcal: 'R005',
  },
  {
    city: 'Valparaíso',
    idcalOld: '39',
    dataInstance: '2016/06/23',
    dir: 'Escuela Naciones Unidas, Pasaje 7 s/n 4º Sector Playa Ancha',
    colaborator: 'Municipalidad de Valparaíso',
    uuid: 'acK7Z1HBOr7jRw3JZhj3',
    idcal: 'R039',
  },
  {
    city: 'Valparaíso',
    idcalOld: '51',
    dataInstance: '2016/06/23',
    dir: 'Junta de Vecino N°104, Cerro Cordillera',
    colaborator: 'Municipalidad de Valparaíso',
    uuid: 'p9XwKUkB7dQVYO7ezgGi',
    idcal: 'R051',
  },
  {
    city: 'Puchuncaví',
    idcalOld: '30',
    dataInstance: '2016/06/24',
    dir: 'Gimnasio Municipal, José Ramón Pérez con Calle Latorre',
    colaborator: 'Municipalidad de Puchuncaví',
    uuid: 'D67jX1JnLgZH5KoXByFG',
    idcal: 'R030',
  },
  {
    city: 'Valparaíso',
    idcalOld: '40',
    dataInstance: '2016/06/28',
    dir: 'Escuela España, Angamos 151 Cerro Monjas',
    colaborator: 'Municipalidad de Valparaíso',
    uuid: 'ay6DiB6BOLW4dOAEsMUV',
    idcal: 'R040',
  },
  {
    city: 'Valparaíso',
    idcalOld: '54',
    dataInstance: '2016/06/30',
    dir: 'Escuela Alemania, Av. Argentina 455',
    colaborator: 'Municipalidad de Valparaíso',
    uuid: 'rLHfK5fstMqsNHnfHKIu',
    idcal: 'R054',
  },
  {
    city: 'Valparaíso',
    idcalOld: '53',
    dataInstance: '2016/07/04',
    dir: 'Escuela Alemania, Av. Argentina 455',
    colaborator: 'Municipalidad de Valparaíso',
    uuid: 'uMdirHUlrxFHmwfvdT6H',
    idcal: 'R053',
  },
  {
    city: 'Quintero',
    idcalOld: '10',
    dataInstance: '2016/07/06',
    dir: 'Salón Fco. Coloane, Estrella de Chile s/n',
    colaborator: 'Municipalidad de Quintero',
    uuid: 'AX8Dg8yxR5tD6WEaPjcC',
    idcal: 'R010',
  },
  {
    city: 'Viña del Mar',
    idcalOld: '42',
    dataInstance: '2016/07/11',
    dir: 'Teatro Municipal',
    colaborator: 'Municipalidad de Viña del Mar',
    uuid: 'oy44PbA5Ra13bWF8akEA',
    idcal: 'R042',
  },
  {
    city: 'Viña del Mar',
    idcalOld: '43',
    dataInstance: '2016/07/11',
    dir: 'Gimnasio Miraflores esq. El Lúcumo, Miraflores',
    colaborator: 'Municipalidad de Viña del Mar',
    uuid: '4qQd5kZugKkDWB7B7F44',
    idcal: 'R043',
  },
  {
    city: 'Viña del Mar',
    idcalOld: '49',
    dataInstance: '2016/07/18',
    dir: 'UNCO de Achupallas, Carlos Ibáñez del Campo N°1000',
    colaborator: 'Municipalidad de Viña del Mar',
    uuid: 'eAQBarzVl6mGgxJmjSRG',
    idcal: 'R049',
  },
  {
    city: 'Viña del Mar',
    idcalOld: '65',
    dataInstance: '2016/07/25',
    dir: 'JV G.R.Shcneiders Sector 1, 2 Norte Esquina 1/2 Poniente, Gómez Carreño',
    colaborator: 'Municipalidad de Viña del Mar',
    uuid: 'oyBwJ8WUThyzMzfaemTI',
    idcal: 'R065',
  },
  {
    city: 'Limache',
    idcalOld: '27',
    dataInstance: '2016/07/27',
    dir: 'Salón de Artes, Av. Urmeneta s/n, frente Parque Brasil',
    colaborator: 'Municipalidad de Limache',
    uuid: 'hJPE5A0t92HH05VupS7h',
    idcal: 'R027',
  },
  {
    city: 'La Cruz',
    idcalOld: '33',
    dataInstance: '2016/07/28',
    dir: 'Centro Comunitario Rolando Arcos, av. 21 Mayo Paradero 18',
    colaborator: 'Municipalidad de La Cruz',
    uuid: 'XapDIu9Z4LuOkAcuXzjj',
    idcal: 'R033',
  },
  {
    city: 'Quilpué',
    idcalOld: '31',
    dataInstance: '2016/07/29',
    dir: 'Liceo Gronemeyer, Calle David Cortes N°1015',
    colaborator: 'Municipalidad de Quilpué',
    uuid: 'gV04NtWGrTPNzIz5ORX8',
    idcal: 'R031',
  },
  {
    city: 'Hijuelas',
    idcalOld: '69',
    dataInstance: '2016/08/02',
    dir: 'Población Swen Krarup, Eucaliptos 980',
    colaborator: 'Municipalidad de Hijuelas',
    uuid: 'aqLIGjQhUopyjGvI1YPG',
    idcal: 'R069',
  },
  {
    city: 'Valparaíso',
    idcalOld: '70',
    dataInstance: '2016/08/04',
    dir: 'Salón Iglesia San Vicente de Paul, Calle Sierra s/n',
    colaborator: 'Municipalidad de Valparaíso',
    uuid: 'ARgxosI7HTjiN5wMz8Z6',
    idcal: 'R070',
  },
  {
    city: 'Calle Larga',
    idcalOld: '21',
    dataInstance: '2016/08/09',
    dir: 'Centro Cultural Pedro Aguirre Cerda, Pocuro s/n',
    colaborator: 'Municipalidad de Calle Larga',
    uuid: 'NZIgGkqnYU7OuMx5uFVz',
    idcal: 'R021',
  },
  {
    city: 'Valparaíso',
    idcalOld: '67',
    dataInstance: '2016/08/10',
    dir: 'Salón de Honor Municipal, Condell 1490',
    colaborator: 'Municipalidad de Valparaíso',
    uuid: 'NUi4XrBq7PZ2t6pQriqP',
    idcal: 'R067',
  },
  {
    city: 'La Cruz',
    idcalOld: '68',
    dataInstance: '2016/08/11',
    dir: 'Centro Comunitario Rolando Arcos, av. 21 Mayo Paradero 18',
    colaborator: 'Municipalidad de La Cruz',
    uuid: '4tOq80sT3RM1AWMAlJvh',
    idcal: 'R068',
  },
  {
    city: 'Quillota',
    idcalOld: '76',
    dataInstance: '2016/08/12',
    dir: 'Blanco N°900, sector Corvi',
    colaborator: 'Municipalidad de Quillota',
    uuid: 'XHiRwAYajqDX2pxSUXWX',
    idcal: 'R076',
  },
  {
    city: 'Nogales',
    idcalOld: '29',
    dataInstance: '2016/08/16',
    dir: 'Casa de la Cultura del Melón',
    colaborator: 'Municipalidad de Nogales',
    uuid: '6QXMwt6vkFT9u3xvxG53',
    idcal: 'R029',
  },
  {
    city: 'Hijuelas',
    idcalOld: '71',
    dataInstance: '2016/08/17',
    dir: 'JJVV de Rabuco, Pasaje San Raimundo s/n, Rabuco',
    colaborator: 'Municipalidad de Hijuelas',
    uuid: '3NbKjFlPsXJP1UWPhyav',
    idcal: 'R071',
  },
  {
    city: 'Valparaíso',
    idcalOld: '77',
    dataInstance: '2016/08/18',
    dir: 'Escuela Jorge Alessandri ,San Roque',
    colaborator: 'Municipalidad de Valparaíso',
    uuid: 'jE2o2YxHo5J8nxyAch4m',
    idcal: 'R077',
  },
  {
    city: 'Hijuelas',
    idcalOld: '82',
    dataInstance: '2016/08/22',
    dir: 'Colegio Pilos de Hualcapo, el Badén, Callejón Los Cachos ',
    colaborator: 'Municipalidad de Hijuelas',
    uuid: 'XeYik2x3sAp6dxx6Lj5b',
    idcal: 'R082',
  },
  {
    city: 'Valparaíso',
    idcalOld: '78',
    dataInstance: '2016/08/24',
    dir: 'Escuela David Ben Gurion, Demostenes 237, Cerro Las Cañas',
    colaborator: 'Municipalidad de Valparaíso',
    uuid: 'Pn7Bgndi01QIOzJ3rJCp',
    idcal: 'R078',
  },
  {
    city: 'San Felipe',
    idcalOld: '19',
    dataInstance: '2016/08/25',
    dir: 'Teatro Municipal, Salinas N°1211',
    colaborator: 'Municipalidad de San Felipe',
    uuid: 'SKn5CGY40rckIIiLVAte',
    idcal: 'R019',
  },
  {
    city: 'Villa Alemana',
    idcalOld: '32',
    dataInstance: '2016/08/30',
    dir: 'Teatro Municipal Pompeya, Paseo Peatonal Los Héroes',
    colaborator: 'Municipalidad de Villa Alemana',
    uuid: 'G0GOmi2NCq4yqYUAtK6J',
    idcal: 'R032',
  },
  {
    city: 'Quintero',
    idcalOld: '72',
    dataInstance: '2016/08/31',
    dir: 'y 17:00 en el Centro Francisco Coloane Estrella de Chile S/N',
    colaborator: 'Municipalidad de Quintero',
    uuid: 'zQpUUjSJjAtnAQFg0cVT',
    idcal: 'R072',
  },
  {
    city: 'Hijuelas',
    idcalOld: '75',
    dataInstance: '2016/09/05',
    dir: 'JJVV Villa Prat, Maitenes, Hijuelas',
    colaborator: 'Municipalidad de Hijuelas',
    uuid: 'rjKrnmhlLGeU1wXwMUJj',
    idcal: 'R075',
  },
  {
    city: 'Quillota',
    idcalOld: '83',
    dataInstance: '2016/09/06',
    dir: 'Gimnasio Municipal, Blanco N°900, Corvi',
    colaborator: 'Municipalidad de Quillota',
    uuid: 'RztGCKQMLRgh8aszL2fg',
    idcal: 'R083',
  },
  {
    city: 'Quintero',
    idcalOld: '86',
    dataInstance: '2016/09/08',
    dir: 'y 17:00 en el Centro Francisco Coloane Estrella de Chile S/N',
    colaborator: 'Municipalidad de Quintero',
    uuid: 'qy4GLxyhGa6K7Zhd2g2I',
    idcal: 'R086',
  },
  {
    city: 'Quintero',
    idcalOld: '88',
    dataInstance: '2016/09/13',
    dir: 'y 17:00 en el Centro Francisco Coloane Estrella de Chile S/N',
    colaborator: 'Municipalidad de Quintero',
    uuid: 'N5jVCICLtNBZ7o4xGwod',
    idcal: 'R088',
  },
  {
    city: 'Valparaíso',
    idcalOld: '89',
    dataInstance: '2016/09/14',
    dir: 'Primero de mayo N°25 Población Maria Eislers C° Placeres',
    colaborator: 'Municipalidad de Valparaíso',
    uuid: 'S5KPwgKz0xBqt7nsLP5P',
    idcal: 'R089',
  },
  {
    city: 'Viña del Mar',
    idcalOld: '90',
    dataInstance: '2016/09/14',
    dir: 'Rio San Pedro N°255 Proyecto Habitacional Parcela 11',
    colaborator: 'Municipalidad de Viña del Mar',
    uuid: '7A7A0obaKtUcUZvNSwAt',
    idcal: 'R090',
  },
  {
    city: 'La Calera',
    idcalOld: '87',
    dataInstance: '2016/09/15',
    dir: 'Salón municipal, Marathon N°312',
    colaborator: 'Municipalidad de La Calera',
    uuid: 'S3Mt6iaeeRLWqJJEyGav',
    idcal: 'R087',
  },
  {
    city: 'Quintero',
    idcalOld: '91',
    dataInstance: '2016/11/22',
    dir: 'y 17:00 en Salón Fco. Coloane, Estrella de Chile s/n',
    colaborator: 'Municipalidad de Quintero',
    uuid: 'YeqlxHZ6ftrrEUVXqz5F',
    idcal: 'R091',
  },
  {
    city: 'Valparaíso',
    idcalOld: '229',
    dataInstance: '2016/12/31',
    dir: 'Fichas sin registro EXCEL 2016',
    colaborator: 'Municipalidad de Valparaíso',
    uuid: 'CkmeBicjhISBy2ZxyLw5',
    idcal: 'R229',
  },
  {
    city: 'La Ligua',
    idcalOld: '92',
    dataInstance: '2017/01/24',
    dir: 'Centro Cívico de la Ligua, Calle Pedro Polanco s/n Ex- Recinto Estación',
    colaborator: 'Municipalidad de La Ligua',
    uuid: 'dSoTcWuukuIMS3t71M6m',
    idcal: 'R092',
  },
  {
    city: 'Valparaíso',
    idcalOld: '93',
    dataInstance: '2017/02/03',
    dir: 'Población Alto Rodelillo Norte y Sur',
    colaborator: 'Municipalidad de Valparaíso',
    uuid: 'xXrB2vIyOkDjAUURxLO8',
    idcal: 'R093',
  },
  {
    city: 'Valparaíso',
    idcalOld: '94',
    dataInstance: '2017/02/11',
    dir: 'Afectados incencio Valparaíso r1',
    colaborator: 'Municipalidad de Valparaíso',
    uuid: 'vKVrRdV8TBTHQ2JlFChA',
    idcal: 'R094',
  },
  {
    city: 'Casablanca',
    idcalOld: '96',
    dataInstance: '2017/03/22',
    dir: 'Salón Municipal, Avenida Portales N°2',
    colaborator: 'Municipalidad de Casablanca',
    uuid: 'g26JxnmYlAid1J5bInpn',
    idcal: 'R096',
  },
  {
    city: 'Juan Fernández',
    idcalOld: '44',
    dataInstance: '2017/04/20',
    dir: 'Caleta de Pescadores Isla Robinson Crusoe',
    colaborator: 'Municipalidad de Juan Fernández',
    uuid: 'xl7PiJ34waY6fqC9yesn',
    idcal: 'R044',
  },
  {
    city: 'Puchuncaví',
    idcalOld: '98',
    dataInstance: '2017/04/25',
    dir: 'Gimnasio Municipal Puchuncaví , Sede Bello Horizonte 12:30 Hrs',
    colaborator: 'Municipalidad de Puchuncaví',
    uuid: 'vjqXTOdx6zthG2rsJbpu',
    idcal: 'R098',
  },
  {
    city: 'Quillota',
    idcalOld: '111',
    dataInstance: '2017/05/10',
    dir: 'y 19:30 en Avenida Dueñas 143, San Pedro',
    colaborator: 'Municipalidad de Quillota',
    uuid: 'g0IKk6a953T42qIF2Lxn',
    idcal: 'R111',
  },
  {
    city: 'Puchuncaví',
    idcalOld: '136',
    dataInstance: '2017/05/15',
    dir: 'Entrega Mobilidad',
    colaborator: 'Municipalidad de Puchuncaví',
    uuid: 'FsATCQwXMcdcwyW0BGks',
    idcal: 'R136',
  },
  {
    city: 'La Calera',
    idcalOld: '106',
    dataInstance: '2017/05/16',
    dir: 'Salón municipal, Marathon N°312',
    colaborator: 'Municipalidad de La Calera',
    uuid: 'KpN97D2svevOtpeTYCIj',
    idcal: 'R106',
  },
  {
    city: 'La Calera',
    idcalOld: '107',
    dataInstance: '2017/05/16',
    dir: 'y 17:00hrs en el Salón municipal, Marathon N°312',
    colaborator: 'Municipalidad de La Calera',
    uuid: 'O95MceEx7FES4ONVcfOG',
    idcal: 'R107',
  },
  {
    city: 'Quintero',
    idcalOld: '100',
    dataInstance: '2017/05/17',
    dir: 'Salón Fco. Coloane, Estrella de Chile s/n',
    colaborator: 'Municipalidad de Quintero',
    uuid: 'kFPUMco0D3JdeneXoxKP',
    idcal: 'R100',
  },
  {
    city: 'Hijuelas',
    idcalOld: '116',
    dataInstance: '2017/05/18',
    dir: 'Calle Verónica Rossat s/n, Villa Las Palmas',
    colaborator: 'Municipalidad de Hijuelas',
    uuid: 'fKSe2YgUfgkF1JVA1TNX',
    idcal: 'R116',
  },
  {
    city: 'Villa Alemana',
    idcalOld: '102',
    dataInstance: '2017/05/23',
    dir: 'Salón Rotary Club, calle P.Lynch frente al Registro Civil',
    colaborator: 'Municipalidad de Villa Alemana',
    uuid: '7W5mRFjJFQp1KllEqwHh',
    idcal: 'R102',
  },
  {
    city: 'Isla de Pascua',
    idcalOld: '45',
    dataInstance: '2017/05/30',
    dir: 'Simón Paoa s/n y 16:40 en el Centro Cultural Tongariki',
    colaborator: 'Municipalidad de Isla de Pascua',
    uuid: 'fF1dD9ZY5f1YPUW1s6GN',
    idcal: 'R045',
  },
  {
    city: 'La Cruz',
    idcalOld: '109',
    dataInstance: '2017/06/09',
    dir: 'Centro de Desarrollo Rolando Arcos, av. 21 de Mayo N°5970',
    colaborator: 'Municipalidad de La Cruz',
    uuid: 'VZx8sFcxdCwpdhXYR0bi',
    idcal: 'R109',
  },
  {
    city: 'Los Andes',
    idcalOld: '114',
    dataInstance: '2017/06/14',
    dir: 'y 15:00, en la Biblioteca Municipal, Av. Independencia N°594',
    colaborator: 'Municipalidad de Los Andes',
    uuid: 'ECcWkPafl4qgby3wxRmu',
    idcal: 'R114',
  },
  {
    city: 'Quilpué',
    idcalOld: '123',
    dataInstance: '2017/06/14',
    dir: 'Sede Roberto Bravo II, Calle Del Trabajador 1141 , Belloto Norte',
    colaborator: 'Municipalidad de Quilpué',
    uuid: '7s3HGOTDytYU8LfYGriR',
    idcal: 'R123',
  },
  {
    city: 'San Antonio',
    idcalOld: '108',
    dataInstance: '2017/06/20',
    dir: 'I.P. La Araucana, Calle Gral. Ibañez 1760, Barrancas',
    colaborator: 'Municipalidad de San Antonio',
    uuid: 'I7AdByye7dKzFqsVhpu7',
    idcal: 'R108',
  },
  {
    city: 'Cartagena',
    idcalOld: '110',
    dataInstance: '2017/06/21',
    dir: 'La Casa del Adulto Mayor ubicada en Av. Cartagena #537',
    colaborator: 'Municipalidad de Cartagena',
    uuid: '1L3gPGqwgwatrRnZewJD',
    idcal: 'R110',
  },
  {
    city: 'Puchuncaví',
    idcalOld: '105',
    dataInstance: '2017/06/30',
    dir: 'Gimnasio Municipal Puchuncaví , Sede Bello Horizonte',
    colaborator: 'Municipalidad de Puchuncaví',
    uuid: 'EYbpxJnyKaEeK3FdpkYi',
    idcal: 'R105',
  },
  {
    city: 'Hijuelas',
    idcalOld: '115',
    dataInstance: '2017/07/05',
    dir: 'Salón Municipal, Manuel Rodriguez, N°1665',
    colaborator: 'Municipalidad de Hijuelas',
    uuid: 'T0a2DQZIW9GI7LghfaDZ',
    idcal: 'R115',
  },
  {
    city: 'Petorca',
    idcalOld: '118',
    dataInstance: '2017/07/12',
    dir: 'Salón Cultural Pte. Manuel Montt, Calle Silva Esquina Prat S/N Petorca',
    colaborator: 'Municipalidad de Petorca',
    uuid: 'CFUUnzc1ZN3VX6ADj4hB',
    idcal: 'R118',
  },
  {
    city: 'Panquehue',
    idcalOld: '124',
    dataInstance: '2017/07/13',
    dir: 'y 15:00, en la Sala Cultural del Municipio, Troncal s/n',
    colaborator: 'Municipalidad de Panquehue',
    uuid: '1zZ9oo5wgXgI6cV4beO2',
    idcal: 'R124',
  },
  {
    city: 'Casablanca',
    idcalOld: '126',
    dataInstance: '2017/07/14',
    dir: 'Teatro Municipal, Avenida Portales N°2, con calle Constitución',
    colaborator: 'Municipalidad de Casablanca',
    uuid: 'jpnod0y4pZrcl2u75YoF',
    idcal: 'R126',
  },
  {
    city: 'Putaendo',
    idcalOld: '129',
    dataInstance: '2017/07/20',
    dir: 'y 15:00, en el Centro de Organizaciones Sociales, Camus N°277',
    colaborator: 'Municipalidad de Putaendo',
    uuid: 'HL5CK9sQFrZUAONQkr8i',
    idcal: 'R129',
  },
  {
    city: 'Villa Alemana',
    idcalOld: '122',
    dataInstance: '2017/07/25',
    dir: 'Salón Rotary Club, calle P.Lynch frente al Registro Civil',
    colaborator: 'Municipalidad de Villa Alemana',
    uuid: 'NLRmTWNmpzLzlbNTO7Vq',
    idcal: 'R122',
  },
  {
    city: 'Quillota',
    idcalOld: '135',
    dataInstance: '2017/07/26',
    dir: 'Sede vecinal aconcagua Sur',
    colaborator: 'Municipalidad de Quillota',
    uuid: 'XQ5jxmLa1yoWaYAUFNv4',
    idcal: 'R135',
  },
  {
    city: 'Quillota',
    idcalOld: '146',
    dataInstance: '2017/07/26',
    dir: 'Sede sector Antumapu',
    colaborator: 'Municipalidad de Quillota',
    uuid: 'uGHcKNGe6DACk9rUEIy6',
    idcal: 'R146',
  },
  {
    city: 'Santa María',
    idcalOld: '125',
    dataInstance: '2017/07/27',
    dir: 'Gimnasio Municipal, ubicado en calle Las Palmeras S/n.',
    colaborator: 'Municipalidad de Santa María',
    uuid: 'oxJNHBL9nTFj4wFZTC2i',
    idcal: 'R125',
  },
  {
    city: 'Hijuelas',
    idcalOld: '137',
    dataInstance: '2017/08/02',
    dir: 'Salón Municipal, Manuel Rodriguez, N°1665',
    colaborator: 'Municipalidad de Hijuelas',
    uuid: 'DOEHCs4bj615U6sgVtcU',
    idcal: 'R137',
  },
  {
    city: 'Quillota',
    idcalOld: '131',
    dataInstance: '2017/08/03',
    dir: 'en Avenida Dueñas 143, Centro Cultural de San Pedro, San Pedro',
    colaborator: 'Municipalidad de Quillota',
    uuid: 'mQSpJfAW6kwmfG1CoGjW',
    idcal: 'R131',
  },
  {
    city: 'La Cruz',
    idcalOld: '134',
    dataInstance: '2017/08/03',
    dir: 'Centro de Desarrollo Rolando Arcos, av. 21 de Mayo N°5970',
    colaborator: 'Municipalidad de La Cruz',
    uuid: 'C5RFb7i8j04pnanhULYz',
    idcal: 'R134',
  },
  {
    city: 'Quintero',
    idcalOld: '119',
    dataInstance: '2017/08/10',
    dir: 'Salón Fco. Coloane, Estrella de Chile s/n',
    colaborator: 'Municipalidad de Quintero',
    uuid: 'yxkijW5dqZiO5tmegFhE',
    idcal: 'R119',
  },
  {
    city: 'Quilpué',
    idcalOld: '152',
    dataInstance: '2017/08/17',
    dir: 'Viviendas Serviu',
    colaborator: 'Municipalidad de Quilpué',
    uuid: '4XFPzlSXTX0hkrRba0Kt',
    idcal: 'R152',
  },
  {
    city: 'Los Andes',
    idcalOld: '127',
    dataInstance: '2017/08/22',
    dir: 'y 15:00, en la Biblioteca Municipal, Av. Independencia N°594',
    colaborator: 'Municipalidad de Los Andes',
    uuid: 'BwL3KhzytoDMyQr9IfbE',
    idcal: 'R127',
  },
  {
    city: 'San Felipe',
    idcalOld: '133',
    dataInstance: '2017/08/23',
    dir: 'Teatro Municipal, Salinas N°1211',
    colaborator: 'Municipalidad de San Felipe',
    uuid: '9XwW2de9e982O923wb2R',
    idcal: 'R133',
  },
  {
    city: 'San Felipe',
    idcalOld: '132',
    dataInstance: '2017/08/29',
    dir: 'Teatro Municipal, Salinas N°1211',
    colaborator: 'Municipalidad de San Felipe',
    uuid: 'uZ2P6PVRxy1strrFSHfN',
    idcal: 'R132',
  },
  {
    city: 'Quillota',
    idcalOld: '138',
    dataInstance: '2017/08/31',
    dir: 'Cerro Mayaca',
    colaborator: 'Municipalidad de Quillota',
    uuid: 'BvrtE4Badora5yUWHniJ',
    idcal: 'R138',
  },
  {
    city: 'Casablanca',
    idcalOld: '147',
    dataInstance: '2017/09/01',
    dir: 'Adulto Mayor',
    colaborator: 'Municipalidad de Casablanca',
    uuid: 'vLBgluJhyoWCGARWAGhg',
    idcal: 'R147',
  },
  {
    city: 'Puchuncaví',
    idcalOld: '154',
    dataInstance: '2017/09/01',
    dir: 'Entrega Mobilidad',
    colaborator: 'Municipalidad de Puchuncaví',
    uuid: 'UtvJ4G9lf43dDjLlnk4n',
    idcal: 'R154',
  },
  {
    city: 'Viña del Mar',
    idcalOld: '153',
    dataInstance: '2017/09/04',
    dir: 'Gobernación de Valparaíso',
    colaborator: 'Municipalidad de Viña del Mar',
    uuid: '4L7UhO6IipFt5QqkWKAr',
    idcal: 'R153',
  },
  {
    city: 'Los Andes',
    idcalOld: '128',
    dataInstance: '2017/09/05',
    dir: 'y 15:00, en la Biblioteca Municipal, Av. Independencia N°594',
    colaborator: 'Municipalidad de Los Andes',
    uuid: 'CojdcTNfWM4zwvye1sgp',
    idcal: 'R128',
  },
  {
    city: 'San Esteban',
    idcalOld: '139',
    dataInstance: '2017/09/11',
    dir: 'Salón Municipal, Av. 26 de Diciembre N°654',
    colaborator: 'Municipalidad de San Esteban',
    uuid: 'DZoli4tl0nMzsexpuOim',
    idcal: 'R139',
  },
  {
    city: 'Papudo',
    idcalOld: '143',
    dataInstance: '2017/09/15',
    dir: 'Sede de Discapacitados, avenida Las Salinas de Pullaly s/n, Pullally',
    colaborator: 'Municipalidad de Papudo',
    uuid: 'MRsk34IaaY60Lg8EqjIP',
    idcal: 'R143',
  },
  {
    city: 'Hijuelas',
    idcalOld: '148',
    dataInstance: '2017/09/26',
    dir: 'Sede UNCO Los Maitenes, sector OCOA',
    colaborator: 'Municipalidad de Hijuelas',
    uuid: 'u6BKIDsy3H002rL66375',
    idcal: 'R148',
  },
  {
    city: 'Valparaíso',
    idcalOld: '156',
    dataInstance: '2017/09/26',
    dir: 'Sede Parque El Litre',
    colaborator: 'Municipalidad de Valparaíso',
    uuid: 'BwcFxxBukj7nScVa2xMn',
    idcal: 'R156',
  },
  {
    city: 'Casablanca',
    idcalOld: '157',
    dataInstance: '2017/09/27',
    dir: "JJVV Población Santa Lucía, calle O'HigginsQuintay",
    colaborator: 'Municipalidad de Casablanca',
    uuid: '6Yl5lJvUQFy8ZJytvhDh',
    idcal: 'R157',
  },
  {
    city: 'Puchuncaví',
    idcalOld: '145',
    dataInstance: '2017/09/28',
    dir: 'Sede Club Deportivo Horcón , Horcón',
    colaborator: 'Municipalidad de Puchuncaví',
    uuid: 'mmOBJE2GT0exABq5LEGJ',
    idcal: 'R145',
  },
  {
    city: 'Valparaíso',
    idcalOld: '97',
    dataInstance: '2017/10/02',
    dir: 'Junta Vecinal N°85 Playa Ancha',
    colaborator: 'Municipalidad de Valparaíso',
    uuid: 'xiBfgJTexxF1HcXKUp7h',
    idcal: 'R097',
  },
  {
    city: 'Llayllay',
    idcalOld: '140',
    dataInstance: '2017/10/04',
    dir: 'Teatro Municipal de Llay-llay Manuel Rodríguez sn',
    colaborator: 'Municipalidad de Llayllay',
    uuid: 'Bj1WyrCgniHEzl93FUTz',
    idcal: 'R140',
  },
  {
    city: 'Viña del Mar',
    idcalOld: '160',
    dataInstance: '2017/10/05',
    dir: 'Paradero 5 Santa Julia, Calle Robert Kennedy, Casa 4 Sede Movico',
    colaborator: 'Municipalidad de Viña del Mar',
    uuid: 'U5i5VxlsS47CcVjD4Eo9',
    idcal: 'R160',
  },
  {
    city: 'Valparaíso',
    idcalOld: '164',
    dataInstance: '2017/10/06',
    dir: 'Junta de Vecinos Teresa de Calcuta, Población Juán Pablo II, Cerro Placeres',
    colaborator: 'Municipalidad de Valparaíso',
    uuid: '1HCCzEhlDo6P9h1Gbc3Q',
    idcal: 'R164',
  },
  {
    city: 'Quillota',
    idcalOld: '161',
    dataInstance: '2017/10/10',
    dir: 'Sede Social Leonardo Da Vinci, ubicada en calle Germán Riesco N°1120',
    colaborator: 'Municipalidad de Quillota',
    uuid: 'lF8GiqjkijdKQyzYjInK',
    idcal: 'R161',
  },
  {
    city: 'Calle Larga',
    idcalOld: '158',
    dataInstance: '2017/10/11',
    dir: 'Centro Cultural Pedro Aguirre Cerda, Pocuro s/n',
    colaborator: 'Municipalidad de Calle Larga',
    uuid: 'r6Z2EFS5zq7cH9QQaZl1',
    idcal: 'R158',
  },
  {
    city: 'Rinconada',
    idcalOld: '159',
    dataInstance: '2017/10/11',
    dir: 'Salón Municipal,San Martín #607',
    colaborator: 'Municipalidad de Rinconada',
    uuid: 'hWu1mSx1pcbEp00K8RLq',
    idcal: 'R159',
  },
  {
    city: 'La Cruz',
    idcalOld: '155',
    dataInstance: '2017/10/11',
    dir: 'Centro de Desarrollo Rolando Arcos, av. 21 de Mayo N°5970',
    colaborator: 'Municipalidad de La Cruz',
    uuid: 'I0sq2emYik1F02PY12zV',
    idcal: 'R155',
  },
  {
    city: 'Papudo',
    idcalOld: '162',
    dataInstance: '2017/10/12',
    dir: 'centro Comunitario Villa Marina, Avenida El Coral',
    colaborator: 'Municipalidad de Papudo',
    uuid: 'ccbeoxlgM5AhipNLrBAb',
    idcal: 'R162',
  },
  {
    city: 'Concón',
    idcalOld: '144',
    dataInstance: '2017/10/16',
    dir: 'El Cipres N°70, Sede Vecinal Población Vista al Mar,',
    colaborator: 'Municipalidad de Concón',
    uuid: '0NEc7Os97yeMNINL9PF3',
    idcal: 'R144',
  },
  {
    city: 'Nogales',
    idcalOld: '165',
    dataInstance: '2017/10/16',
    dir: 'Plaza de la Población El Polígono, Nogales',
    colaborator: 'Municipalidad de Nogales',
    uuid: 'HZC5o6SfMqRqF17RASbK',
    idcal: 'R165',
  },
  {
    city: 'Villa Alemana',
    idcalOld: '163',
    dataInstance: '2017/10/18',
    dir: 'Salón Rotary Club, calle P.Lynch frente al Registro Civil',
    colaborator: 'Municipalidad de Villa Alemana',
    uuid: 'wOjZKiua0AytvdSUeiPo',
    idcal: 'R163',
  },
  {
    city: 'Hijuelas',
    idcalOld: '167',
    dataInstance: '2017/11/02',
    dir: 'Vista Hermosa',
    colaborator: 'Municipalidad de Hijuelas',
    uuid: 'UJyOrEbaxcOzTETD1JQn',
    idcal: 'R167',
  },
  {
    city: 'Limache',
    idcalOld: '177',
    dataInstance: '2017/11/07',
    dir: "Sede Vecinal Población Orval-O'Higgins, La concepción con esquina el Canelo",
    colaborator: 'Municipalidad de Limache',
    uuid: 'fC1zoEIEsTyG8Q3B16Yo',
    idcal: 'R177',
  },
  {
    city: 'Viña del Mar',
    idcalOld: '173',
    dataInstance: '2017/11/08',
    dir: 'la Escuela La Parva, calle Estanislao Loayza, paradero 3 1/2, Achupallas',
    colaborator: 'Municipalidad de Viña del Mar',
    uuid: 'Bz6EBmlQlykZwXbo6N4Y',
    idcal: 'R173',
  },
  {
    city: 'San Antonio',
    idcalOld: '171',
    dataInstance: '2017/11/09',
    dir: 'Sede Planicies de Bellavista, Nueva Bruselas 508',
    colaborator: 'Municipalidad de San Antonio',
    uuid: 'lSC6qqzLF9069IDE9hO6',
    idcal: 'R171',
  },
  {
    city: 'Valparaíso',
    idcalOld: '179',
    dataInstance: '2017/11/11',
    dir: 'Sede Asociación de Futbol Pedro Aguirre Cerda',
    colaborator: 'Municipalidad de Valparaíso',
    uuid: 'Y6DWvvXlikcH8ewwjHGK',
    idcal: 'R179',
  },
  {
    city: 'Valparaíso',
    idcalOld: '169',
    dataInstance: '2017/11/13',
    dir: 'Población Merded y Las Cañas, Casona El Pajonal: Calle Merced S/N°, Cerro Merced',
    colaborator: 'Municipalidad de Valparaíso',
    uuid: 'hpkryAA4t9H7HABuA6gD',
    idcal: 'R169',
  },
  {
    city: 'Nogales',
    idcalOld: '181',
    dataInstance: '2017/11/28',
    dir: 'Plaza de la Población El Polígono, Nogales',
    colaborator: 'Municipalidad de Nogales',
    uuid: 'wrdjD5BglLRunVoD9aT7',
    idcal: 'R181',
  },
  {
    city: 'Valparaíso',
    idcalOld: '182',
    dataInstance: '2017/12/02',
    dir: 'Cesfam de Rodelillo: Calle Merced 4350 Rodelillo',
    colaborator: 'Municipalidad de Valparaíso',
    uuid: 'DtNAkmHmjGl4WAm1pgkv',
    idcal: 'R182',
  },
  {
    city: 'Valparaíso',
    idcalOld: '187',
    dataInstance: '2017/12/02',
    dir: 'Cesfam de Rodelillo: Calle Merced 4350 Rodelillo',
    colaborator: 'Municipalidad de Valparaíso',
    uuid: 'wiPcJHxvHguVZxZ3H8U4',
    idcal: 'R187',
  },
  {
    city: 'Viña del Mar',
    idcalOld: '185',
    dataInstance: '2017/12/11',
    dir: 'Comité Salvador Reyes, Mejoramiento de Vivienda',
    colaborator: 'Municipalidad de Viña del Mar',
    uuid: 'C7uNejnmwiLC3x91XqQi',
    idcal: 'R185',
  },
  {
    city: 'Puchuncaví',
    idcalOld: '186',
    dataInstance: '2017/12/11',
    dir: 'Sede Vecinal,Barrio Cruz del Llano.',
    colaborator: 'Municipalidad de Puchuncaví',
    uuid: '6xOBXUOayFhZpdXM56HZ',
    idcal: 'R186',
  },
  {
    city: 'Quintero',
    idcalOld: '188',
    dataInstance: '2017/12/11',
    dir: 'Salón Fco. Coloane, Estrella de Chile s/n',
    colaborator: 'Municipalidad de Quintero',
    uuid: '6QOyF7qIgf1cdDdcHe6H',
    idcal: 'R188',
  },
  {
    city: 'Viña del Mar',
    idcalOld: '191',
    dataInstance: '2017/12/14',
    dir: 'Gobernación',
    colaborator: 'Municipalidad de Viña del Mar',
    uuid: 'GagzF5XpNzLqrTwSd1FJ',
    idcal: 'R191',
  },
  {
    city: 'Viña del Mar',
    idcalOld: '192',
    dataInstance: '2017/12/14',
    dir: 'Monte Sinaí MINVU',
    colaborator: 'Municipalidad de Viña del Mar',
    uuid: 'bhuLd4a3Vesla68ZJpgZ',
    idcal: 'R192',
  },
  {
    city: 'San Antonio',
    idcalOld: '194',
    dataInstance: '2017/12/14',
    dir: 'JJVV 30 de Marzo',
    colaborator: 'Municipalidad de San Antonio',
    uuid: 'iEfTTi6g4LrtJA4PiDl4',
    idcal: 'R194',
  },
  {
    city: 'Valparaíso',
    idcalOld: '230',
    dataInstance: '2017/12/31',
    dir: 'Entregas sin registrar 2017',
    colaborator: 'Municipalidad de Valparaíso',
    uuid: 'fD1HXsnw9TWG2JX6AEVj',
    idcal: 'R230',
  },
  {
    city: 'Valparaíso',
    idcalOld: '195',
    dataInstance: '2018/02/22',
    dir: 'Pob. Francisco I, Placilla, Valparaíso',
    colaborator: 'Municipalidad de Valparaíso',
    uuid: 'hZO5jRT1RJL1t0qOCBa3',
    idcal: 'R195',
  },
  {
    city: 'San Felipe',
    idcalOld: '196',
    dataInstance: '2018/02/22',
    dir: 'Hogar de Ancianos, Tocornal 4311',
    colaborator: 'Municipalidad de San Felipe',
    uuid: 'dj57tFIVcf9vyyMNlibq',
    idcal: 'R196',
  },
  {
    city: 'Viña del Mar',
    idcalOld: '197',
    dataInstance: '2018/03/09',
    dir: 'Población Nueva Aurora, Mujeres',
    colaborator: 'Municipalidad de Viña del Mar',
    uuid: '4BnMghuHfNjysO1V8lke',
    idcal: 'R197',
  },
  {
    city: 'Viña del Mar',
    idcalOld: '199',
    dataInstance: '2018/06/07',
    dir: 'Unidad Vecinal N°100, Av. Gomez Carreño Nº 3340, 5º sector',
    colaborator: 'Municipalidad de Viña del Mar',
    uuid: 'Sj0CQanl97IE1Hv7v5su',
    idcal: 'R199',
  },
  {
    city: 'San Antonio',
    idcalOld: '200',
    dataInstance: '2018/08/16',
    dir: 'Auditorio de la ACHS, en Barros Luco 1575',
    colaborator: 'Municipalidad de San Antonio',
    uuid: 'RIfbVIpJ9XT3Rr8lefKe',
    idcal: 'R200',
  },
  {
    city: 'Viña del Mar',
    idcalOld: '207',
    dataInstance: '2018/09/10',
    dir: 'Gimnasio Reñaca Alto , Calle 9 N°233, paradero 8 1/2, Reñaca Alto',
    colaborator: 'Municipalidad de Viña del Mar',
    uuid: 'cFbDlLMo9R12j7c5WrpO',
    idcal: 'R207',
  },
  {
    city: 'Hijuelas',
    idcalOld: '201',
    dataInstance: '2018/09/25',
    dir: 'Junta Vecinal de Los Tilos, Romeral',
    colaborator: 'Municipalidad de Hijuelas',
    uuid: 'NyXTnr5Ud4meKaFnOgY8',
    idcal: 'R201',
  },
  {
    city: 'La Cruz',
    idcalOld: '202',
    dataInstance: '2018/09/26',
    dir: 'Gimnasio Municipal, 21 de Mayo 5435',
    colaborator: 'Municipalidad de La Cruz',
    uuid: '3OQJZf8ThgnFQGoOkDSq',
    idcal: 'R202',
  },
  {
    city: 'Viña del Mar',
    idcalOld: '208',
    dataInstance: '2018/09/27',
    dir: 'JJVV Las Palmeras, Rogelio Astudillo Nº 22, sector C',
    colaborator: 'Municipalidad de Viña del Mar',
    uuid: 't0A7eZfus8YwXGLqRrSb',
    idcal: 'R208',
  },
  {
    city: 'Viña del Mar',
    idcalOld: '209',
    dataInstance: '2018/10/02',
    dir: 'Complejo Deportivo Miraflores, El Lúcumo s/n',
    colaborator: 'Municipalidad de Viña del Mar',
    uuid: 'ybygTPj50UrtgVN8LtYX',
    idcal: 'R209',
  },
  {
    city: 'Hijuelas',
    idcalOld: '226',
    dataInstance: '2018/10/03',
    dir: 'Sector El Olivo',
    colaborator: 'Municipalidad de Hijuelas',
    uuid: 'NGIbi1hWpbHJpDCSLvRI',
    idcal: 'R226',
  },
  {
    city: 'Viña del Mar',
    idcalOld: '210',
    dataInstance: '2018/10/05',
    dir: 'Escuela Villa Independencia , Calle Gabriela Mistral s/n',
    colaborator: 'Municipalidad de Viña del Mar',
    uuid: 'VcvC21okkxr5OA3cDDA6',
    idcal: 'R210',
  },
  {
    city: 'Viña del Mar',
    idcalOld: '211',
    dataInstance: '2018/10/09',
    dir: 'JJVV K-91, Avenida Inglaterra Nº 635',
    colaborator: 'Municipalidad de Viña del Mar',
    uuid: 'BPFEKjaopFupXDNogJRW',
    idcal: 'R211',
  },
  {
    city: 'Catemu',
    idcalOld: '221',
    dataInstance: '2018/10/10',
    dir: 'Salón Parroquial Iglesia San José, calle Borjas Garcia Huidobro sn',
    colaborator: 'Municipalidad de Catemu',
    uuid: 'oDHL9Lzl967C4cbj4ElC',
    idcal: 'R221',
  },
  {
    city: 'Viña del Mar',
    idcalOld: '227',
    dataInstance: '2018/10/10',
    dir: 'Fosis',
    colaborator: 'Municipalidad de Viña del Mar',
    uuid: 'LXDP2zbFlXCmEmBh3wbk',
    idcal: 'R227',
  },
  {
    city: 'Viña del Mar',
    idcalOld: '212',
    dataInstance: '2018/10/12',
    dir: 'Gimnasio Municipal Glorias Navales, Calle Fragata Esmeralda s/n',
    colaborator: 'Municipalidad de Viña del Mar',
    uuid: 'zcvoJHrmEwgbeU85wVSM',
    idcal: 'R212',
  },
  {
    city: 'Santa María',
    idcalOld: '225',
    dataInstance: '2018/10/17',
    dir: 'E-713 1326, Gimnacio Municipal',
    colaborator: 'Municipalidad de Santa María',
    uuid: '580P3XPIlWrU52fxyoKR',
    idcal: 'R225',
  },
  {
    city: 'Viña del Mar',
    idcalOld: '213',
    dataInstance: '2018/10/19',
    dir: 'Unión Comunal Viña Oriente , El Tamarugal s/n',
    colaborator: 'Municipalidad de Viña del Mar',
    uuid: 'YPyxMujm0rvVi0S9GmHK',
    idcal: 'R213',
  },
  {
    city: 'Cabildo',
    idcalOld: '224',
    dataInstance: '2018/10/24',
    dir: 'Teatro Municipal',
    colaborator: 'Municipalidad de Cabildo',
    uuid: 'bvJOvKjPwkQJX2IUMBf0',
    idcal: 'R224',
  },
  {
    city: 'Viña del Mar',
    idcalOld: '214',
    dataInstance: '2018/10/25',
    dir: 'Unión Comunal Viña Oriente , El Tamarugal s/n',
    colaborator: 'Municipalidad de Viña del Mar',
    uuid: 'VQCfu790KpjjjfSP6STn',
    idcal: 'R214',
  },
  {
    city: 'Llayllay',
    idcalOld: '223',
    dataInstance: '2018/10/29',
    dir: 'Gimnasio Municipal de Llay Llay',
    colaborator: 'Municipalidad de Llayllay',
    uuid: '0T5elnEmPNrQmjh46Dtp',
    idcal: 'R223',
  },
  {
    city: 'Viña del Mar',
    idcalOld: '216',
    dataInstance: '2018/10/30',
    dir: 'UNCO Achupallas , Av Carlos Ibáñez del Campo Nº 1000 , Paradero 5',
    colaborator: 'Municipalidad de Viña del Mar',
    uuid: 'AILKB2PR4ztPafZ5OSd5',
    idcal: 'R216',
  },
  {
    city: 'Viña del Mar',
    idcalOld: '217',
    dataInstance: '2018/11/06',
    dir: 'Complejo Deportivo , Santiago Watts Nº 231',
    colaborator: 'Municipalidad de Viña del Mar',
    uuid: 'oyIst3xBE89J10T5FrTy',
    idcal: 'R217',
  },
  {
    city: 'La Calera',
    idcalOld: '218',
    dataInstance: '2018/11/08',
    dir: 'Salón Municipal en Marathon 340',
    colaborator: 'Municipalidad de La Calera',
    uuid: 'JawB5VIlpJQBbkTRTSwI',
    idcal: 'R218',
  },
  {
    city: 'Villa Alemana',
    idcalOld: '204',
    dataInstance: '2018/11/08',
    dir: 'Rotary Club',
    colaborator: 'Municipalidad de Villa Alemana',
    uuid: '4o0ryyuo8aMOuVsmxdYu',
    idcal: 'R204',
  },
  {
    city: 'Los Andes',
    idcalOld: '203',
    dataInstance: '2018/11/14',
    dir: 'Biblioteca Municipal, Indepencia 594',
    colaborator: 'Municipalidad de Los Andes',
    uuid: 'zDAOuvEkKpQyMTuhQwv8',
    idcal: 'R203',
  },
  {
    city: 'Viña del Mar',
    idcalOld: '215',
    dataInstance: '2018/11/15',
    dir: 'JJVV Británica , 20 Norte Nº 1784, esq. Calle 4 ',
    colaborator: 'Municipalidad de Viña del Mar',
    uuid: 'aXC7WrAyjkq7pJ7ege2A',
    idcal: 'R215',
  },
  {
    city: 'Zapallar',
    idcalOld: '219',
    dataInstance: '2018/11/15',
    dir: 'en Zapallar Centro',
    colaborator: 'Municipalidad de Zapallar',
    uuid: 'jkIB3XOSxOpSrQK0alhM',
    idcal: 'R219',
  },
  {
    city: 'Viña del Mar',
    idcalOld: '220',
    dataInstance: '2018/11/29',
    dir: 'Condomino Los Ciruelos , Viña del Mar',
    colaborator: 'Municipalidad de Viña del Mar',
    uuid: 'Zzue4giT2j05nTIIfS8b',
    idcal: 'R220',
  },
  {
    city: 'San Esteban',
    idcalOld: '222',
    dataInstance: '2018/11/29',
    dir: 'Gimnasio Municipal de San Esteban',
    colaborator: 'Municipalidad de San Esteban',
    uuid: 'nQkj3tb2JYRIsnrEwS7h',
    idcal: 'R222',
  },
  {
    city: 'Villa Alemana',
    idcalOld: '206',
    dataInstance: '2019/01/22',
    dir: 'Rotary Club Villa Alemana, Avda. Valparaíso 543, acceso por P.Lynch',
    colaborator: 'Municipalidad de Villa Alemana',
    uuid: 'RsR5yQsyUJIR3qDQL8vw',
    idcal: 'R206',
  },
  {
    city: 'Nogales',
    idcalOld: '228',
    dataInstance: '2019/03/13',
    dir: 'Sede JJVV Juanita Fernandez, Calle 1 Nº106, Sector de la Unión,',
    colaborator: 'Municipalidad de Nogales',
    uuid: 'ft5GMotbSwAxXuWSvsIR',
    idcal: 'R228',
  },
  {
    city: 'Valparaíso',
    idcalOld: '232',
    dataInstance: '2019/03/20',
    dir: 'JJVV Del Timonel 6-2, Sector Puertas Negras',
    colaborator: 'Municipalidad de Valparaíso',
    uuid: 'rEZ3Wl15nnpZMXMxmNMN',
    idcal: 'R232',
  },
  {
    city: 'Quintero',
    idcalOld: '233',
    dataInstance: '2019/03/28',
    dir: 'Salón Fco. Coloane, Estrella de Chile s/n',
    colaborator: 'Municipalidad de Quintero',
    uuid: 'pSaYKDe3RChFRK8HsNET',
    idcal: 'R233',
  },
  {
    city: 'La Cruz',
    idcalOld: '234',
    dataInstance: '2019/04/10',
    dir: 'Salón Municipal , 21 de Mayo 5435',
    colaborator: 'Municipalidad de La Cruz',
    uuid: 'DtFKjxq3BwlXNMl7rPSa',
    idcal: 'R234',
  },
  {
    city: 'Nogales',
    idcalOld: '236',
    dataInstance: '2019/04/11',
    dir: 'Aldunate 161, Casa de la Cultura',
    colaborator: 'Municipalidad de Nogales',
    uuid: 'ndf1TjoXDZs8UYNHZWIH',
    idcal: 'R236',
  },
  {
    city: 'Quintero',
    idcalOld: '238',
    dataInstance: '2019/04/18',
    dir: 'Sede JJVV Santa Luisa calle Santa Luisa',
    colaborator: 'Municipalidad de Quintero',
    uuid: 'EQITZDvePO6pgRPXmPyf',
    idcal: 'R238',
  },
  {
    city: 'La Calera',
    idcalOld: '242',
    dataInstance: '2019/04/23',
    dir: 'Salón municipal, Marathon N°312',
    colaborator: 'Municipalidad de La Calera',
    uuid: 'eXkCbEyH0uaY9QETu7dv',
    idcal: 'R242',
  },
  {
    city: 'Nogales',
    idcalOld: '237',
    dataInstance: '2019/04/25',
    dir: 'Sede Vecinal Santa Isabel del Melón',
    colaborator: 'Municipalidad de Nogales',
    uuid: 'APE8gXzO97DCq8dZFHJa',
    idcal: 'R237',
  },
  {
    city: 'Valparaíso',
    idcalOld: '244',
    dataInstance: '2019/05/07',
    dir: 'JJVV Del Timonel 6-2, Sector Puertas Negras',
    colaborator: 'Municipalidad de Valparaíso',
    uuid: 'OXOqT8AKUqJMIjFV1ha3',
    idcal: 'R244',
  },
  {
    city: 'Cabildo',
    idcalOld: '239',
    dataInstance: '2019/05/08',
    dir: 'Teatro Municipal de Cabildo, Calle Lautaro s/n',
    colaborator: 'Municipalidad de Cabildo',
    uuid: '2B3MkkivFLgwcCee7Jyq',
    idcal: 'R239',
  },
  {
    city: 'Puchuncaví',
    idcalOld: '240',
    dataInstance: '2019/05/13',
    dir: "Casa de La Cultura, Av. B.O'Higgins 140",
    colaborator: 'Municipalidad de Puchuncaví',
    uuid: 'mEEUE2vBR6wW97rRVsCX',
    idcal: 'R240',
  },
  {
    city: 'Catemu',
    idcalOld: '235',
    dataInstance: '2019/05/15',
    dir: 'Sede Vecinal sector El Cobre s/n',
    colaborator: 'Municipalidad de Catemu',
    uuid: 'oQFXCkilUvNFlPGwiLxS',
    idcal: 'R235',
  },
  {
    city: 'Quintero',
    idcalOld: '241',
    dataInstance: '2019/05/16',
    dir: 'Sede Vecinal de Valle Alegre',
    colaborator: 'Municipalidad de Quintero',
    uuid: 'P5wS2fEhpmROF8TXcs8r',
    idcal: 'R241',
  },
  {
    city: 'Villa Alemana',
    idcalOld: '256',
    dataInstance: '2019/05/30',
    dir: 'Gimnasio Luis Cruz Martinez, Baquedano 1083',
    colaborator: 'Municipalidad de Villa Alemana',
    uuid: 'Gqp02xsgreaiAtfYBXOT',
    idcal: 'R256',
  },
  {
    city: 'Limache',
    idcalOld: '257',
    dataInstance: '2019/05/31',
    dir: 'Palmira Romano Sur 340',
    colaborator: 'Municipalidad de Limache',
    uuid: 'JEF7dBIHs0TtU5lroaz5',
    idcal: 'R257',
  },
  {
    city: 'Panquehue',
    idcalOld: '245',
    dataInstance: '2019/06/04',
    dir: 'Aún sin definir',
    colaborator: 'Municipalidad de Panquehue',
    uuid: 'xLpSVoQ4gbI3M1TWEJJx',
    idcal: 'R245',
  },
  {
    city: 'Quillota',
    idcalOld: '247',
    dataInstance: '2019/06/05',
    dir: 'Viviendas Tuteladas, Jose Miguel Carrera S/N',
    colaborator: 'Municipalidad de Quillota',
    uuid: 'oY8yh2ACBRQmDStKS8Sm',
    idcal: 'R247',
  },
  {
    city: 'Concón',
    idcalOld: '243',
    dataInstance: '2019/06/07',
    dir: 'Escuela Puente Colmo, Camino Internacional s/n',
    colaborator: 'Municipalidad de Concón',
    uuid: 'UFxhB7CIrOK8CuaXizLL',
    idcal: 'R243',
  },
  {
    city: 'Petorca',
    idcalOld: '254',
    dataInstance: '2019/06/11',
    dir: 'Sede Vecinal Valle Los Olmos, Ruta E375 s/n',
    colaborator: 'Municipalidad de Petorca',
    uuid: 'mQfTBS79FSbzlNKv1Sdx',
    idcal: 'R254',
  },
  {
    city: 'Valparaíso',
    idcalOld: '255',
    dataInstance: '2019/06/11',
    dir: 'Del Timonel 6-2, Puertas Negras, Valparaíso',
    colaborator: 'Municipalidad de Valparaíso',
    uuid: 'oeFnBh4XK9UiE9OFExBG',
    idcal: 'R255',
  },
  {
    city: 'Nogales',
    idcalOld: '258',
    dataInstance: '2019/06/14',
    dir: 'Aldunate 161, Casa de la Cultura',
    colaborator: 'Municipalidad de Nogales',
    uuid: 'uszYzlYhm1mPyGa07XYi',
    idcal: 'R258',
  },
  {
    city: 'La Ligua',
    idcalOld: '253',
    dataInstance: '2019/06/19',
    dir: 'Viviendas Tuteladas, Manuel Antonio Gaete N° 135',
    colaborator: 'Municipalidad de La Ligua',
    uuid: 'bd35bI8vw77zH2I413BV',
    idcal: 'R253',
  },
  {
    city: 'Llayllay',
    idcalOld: '252',
    dataInstance: '2019/06/25',
    dir: 'Viviendas Tuteladas, Calle San Ignacio N° 379',
    colaborator: 'Municipalidad de Llayllay',
    uuid: 'MWbAm1aG4XkCOZEk0a9V',
    idcal: 'R252',
  },
  {
    city: 'Hijuelas',
    idcalOld: '231',
    dataInstance: '2019/06/26',
    dir: 'Calle Cuatro Esquinas Nro 1235',
    colaborator: 'Municipalidad de Hijuelas',
    uuid: 'D0PHe9q0ijmL8d4uqosQ',
    idcal: 'R231',
  },
  {
    city: 'El Tabo',
    idcalOld: '250',
    dataInstance: '2019/07/01',
    dir: 'Calle Las Salinas N° 105',
    colaborator: 'Municipalidad de El Tabo',
    uuid: '8rNHMHZu5lShCspWdDFj',
    idcal: 'R250',
  },
  {
    city: 'San Antonio',
    idcalOld: '251',
    dataInstance: '2019/07/01',
    dir: 'Viviendas Tuteladas , Regidor Luis Norambuena N° 442',
    colaborator: 'Municipalidad de San Antonio',
    uuid: 'ngVBCOhwsOJD2vsnVGVH',
    idcal: 'R251',
  },
  {
    city: 'Panquehue',
    idcalOld: '266',
    dataInstance: '2019/07/01',
    dir: 'Biblioteca Municipal, Las Chilcas Pasaje 3, Sector La Pirca',
    colaborator: 'Municipalidad de Panquehue',
    uuid: 'U57ZUdLzI1HjbHbathGm',
    idcal: 'R266',
  },
  {
    city: 'Quintero',
    idcalOld: '259',
    dataInstance: '2019/07/01',
    dir: 'Loncura',
    colaborator: 'Municipalidad de Quintero',
    uuid: 'GB44CMvmlUSeaPpO7GO1',
    idcal: 'R259',
  },
  {
    city: 'Viña del Mar',
    idcalOld: '260',
    dataInstance: '2019/07/10',
    dir: 'Sede JJVV Miraflores Alto, Bellavista 1663, Miraflores Alto',
    colaborator: 'Municipalidad de Viña del Mar',
    uuid: 'Nq9ZuXFh96BM9urhGtc8',
    idcal: 'R260',
  },
  {
    city: 'Viña del Mar',
    idcalOld: '261',
    dataInstance: '2019/07/12',
    dir: 'JJVV Libertad , Av Pacifico 4355, 2º Sector Gómez Carreño',
    colaborator: 'Municipalidad de Viña del Mar',
    uuid: 'IRod4L090N9A0WGs3fNZ',
    idcal: 'R261',
  },
  {
    city: 'Viña del Mar',
    idcalOld: '262',
    dataInstance: '2019/08/22',
    dir: 'Calle Concepción 530, Esq. Chile Sur, Nueva Aurora',
    colaborator: 'Municipalidad de Viña del Mar',
    uuid: '0Ivu93DK2t3o9jgjyoyj',
    idcal: 'R262',
  },
  {
    city: 'Viña del Mar',
    idcalOld: '263',
    dataInstance: '2019/10/09',
    dir: 'Calle Destructor HYATT Nro 203, Glorias Navales',
    colaborator: 'Municipalidad de Viña del Mar',
    uuid: 'Sjk6rAtTqKxb4juRybmF',
    idcal: 'R263',
  },
  {
    city: 'Quintero',
    idcalOld: '267',
    dataInstance: '2019/11/05',
    dir: 'Loncura, Quintero',
    colaborator: 'Municipalidad de Quintero',
    uuid: 'GaDTIVhYjgR8q0okd4kF',
    idcal: 'R267',
  },
  {
    city: 'Viña del Mar',
    idcalOld: '264',
    dataInstance: '2019/12/03',
    dir: 'UV Cardenal Caro, Av. Principal 78, Chorrillos',
    colaborator: 'Municipalidad de Viña del Mar',
    uuid: 'lAbERliSJhNuwuoPdvtC',
    idcal: 'R264',
  },
  {
    city: 'San Esteban',
    idcalOld: '268',
    dataInstance: '2019/12/18',
    dir: 'Salón Terma del Corazón, Ruta E-761 km 18',
    colaborator: 'Municipalidad de San Esteban',
    uuid: 'xnKP9WcIn6gXpM01PQNo',
    idcal: 'R268',
  },
  {
    city: 'Viña del Mar',
    idcalOld: '265',
    dataInstance: '2019/12/19',
    dir: 'JJVV Eduardo Titus, Av. Blanca Vergara S/N, Forestal',
    colaborator: 'Municipalidad de Viña del Mar',
    uuid: 'rXoNex3mVo06U9UZsNVC',
    idcal: 'R265',
  },
  {
    city: 'Viña del Mar',
    idcalOld: '269',
    dataInstance: '2019/12/20',
    dir: 'Aún sin definir',
    colaborator: 'Municipalidad de Viña del Mar',
    uuid: 'EONDzAW8NbC2qaZOTUYt',
    idcal: 'R269',
  },
  {
    city: 'Viña del Mar',
    idcalOld: '270',
    dataInstance: '2020/01/06',
    dir: 'JJVV Primer Sector Gomez Carreño, Calle Austral Nº4900',
    colaborator: 'Municipalidad de Viña del Mar',
    uuid: 'AQruhpNfM5vPqRK1yMox',
    idcal: 'R270',
  },
  {
    city: 'Olmué',
    idcalOld: '272',
    dataInstance: '2020/10/29',
    dir: 'Centro Natura , Pasaje Cabrería n°2681 con calle La Gruta',
    colaborator: 'Municipalidad de Olmué',
    uuid: 'DEV8e7zfAyRJO0NQQKRy',
    idcal: 'R272',
  },
  {
    city: 'La Ligua',
    idcalOld: '277',
    dataInstance: '2020/11/12',
    dir: 'Prodemu La Ligua',
    colaborator: 'Municipalidad de La Ligua',
    uuid: 'P8bKlaoMpQFJP0Wdrcrd',
    idcal: 'R277',
  },
  {
    city: 'Villa Alemana',
    idcalOld: '273',
    dataInstance: '2020/12/04',
    dir: 'Salón Rotary Club, ingreso por calle P.Lynch frente al Registro Civil',
    colaborator: 'Municipalidad de Villa Alemana',
    uuid: 'vYG9rAuaRNI5tCj2yI8n',
    idcal: 'R273',
  },
  {
    city: 'Cabildo',
    idcalOld: '278',
    dataInstance: '2020/12/10',
    dir: 'Liceo Polivalente NoA2, calle Zoila Gac Nro 639',
    colaborator: 'Municipalidad de Cabildo',
    uuid: 'hMlWqh0xgPHkKkZL3fe5',
    idcal: 'R278',
  },
  {
    city: 'Olmué',
    idcalOld: '276',
    dataInstance: '2020/12/15',
    dir: 'Pasaje Cabrería n°2681 con calle La Gruta,Olmué',
    colaborator: 'Municipalidad de Olmué',
    uuid: 'ElVxKm62mq9MwAWiwpvG',
    idcal: 'R276',
  },
  {
    city: 'Quintero',
    idcalOld: '275',
    dataInstance: '2020/12/16',
    dir: 'Auditorio Daem, Calle Arturo Prat 1960',
    colaborator: 'Municipalidad de Quintero',
    uuid: 'nPXl6IyfICD2KYqgJHLJ',
    idcal: 'R275',
  },
  {
    city: 'Concón',
    idcalOld: '279',
    dataInstance: '2020/12/16',
    dir: 'Centro Comunitario, calle Yañez N°827',
    colaborator: 'Municipalidad de Concón',
    uuid: 'rco4V5sUkfdOU5kza0Ty',
    idcal: 'R279',
  },
  {
    city: 'Villa Alemana',
    idcalOld: '280',
    dataInstance: '2021/01/08',
    dir: 'Patio Municipal, Edificio Consistorial',
    colaborator: 'Municipalidad de Villa Alemana',
    uuid: 'B2htPVUZAOVmAp6w2gNt',
    idcal: 'R280',
  },
  {
    city: 'Limache',
    idcalOld: '281',
    dataInstance: '2021/02/09',
    dir: 'Cesfam de Limache Viejo, Andres Bello 511',
    colaborator: 'Municipalidad de Limache',
    uuid: '3JJFFyuCCq6zJcE11pqF',
    idcal: 'R281',
  },
  {
    city: 'La Cruz',
    idcalOld: '274',
    dataInstance: '2021/02/18',
    dir: 'Colegio María Alonso Chacón',
    colaborator: 'Municipalidad de La Cruz',
    uuid: 'eIbPtSGKeNxh7jdkXL22',
    idcal: 'R274',
  },
  {
    city: 'Hijuelas',
    idcalOld: '283',
    dataInstance: '2021/02/25',
    dir: 'Tres Esquinas, Sector Rene Pianovi',
    colaborator: 'Municipalidad de Hijuelas',
    uuid: 'pRkwYeZ6lqnOh5JjGtiX',
    idcal: 'R283',
  },
  {
    city: 'Quintero',
    idcalOld: '282',
    dataInstance: '2021/03/03',
    dir: 'Plaza Segura, Calle E.Lillo con 18 de septiembre',
    colaborator: 'Municipalidad de Quintero',
    uuid: 'xRDWXBe6rdRnwoqxorFR',
    idcal: 'R282',
  },
  {
    city: 'Limache',
    idcalOld: '286',
    dataInstance: '2021/03/04',
    dir: 'Escuela nro. 88, ubicada en Avenida Urmeneta 255',
    colaborator: 'Municipalidad de Limache',
    uuid: 'O3XOM5CdpK7qCJ03EKeo',
    idcal: 'R286',
  },
  {
    city: 'Los Andes',
    idcalOld: '284',
    dataInstance: '2021/03/09',
    dir: 'vía Zoom Prodemu',
    colaborator: 'Prodemu Los Andes',
    uuid: '6pRDZHOQFl0gjgm0Ieuv',
    idcal: 'R284',
  },
  {
    city: 'Quilpué',
    idcalOld: '285',
    dataInstance: '2021/03/09',
    dir: 'vía Zoom Prodemu',
    colaborator: 'Prodemu Marga Marga',
    uuid: '7unzMAgTwFPVi6YkoyQX',
    idcal: 'R285',
  },
  {
    city: 'Cabildo',
    idcalOld: '287',
    dataInstance: '2021/03/10',
    dir: 'Centro Casa López, Humeres 596',
    colaborator: 'Municipalidad de Cabildo',
    uuid: '4UnoMDOlaPeIBahcKrl8',
    idcal: 'R287',
  },
  {
    city: 'San Antonio',
    idcalOld: '288',
    dataInstance: '2021/03/23',
    dir: 'vía Zoom Prodemu San Antonio',
    colaborator: 'Prodemu San Antonio',
    uuid: 'dCmBEty0eeoVWZhsQKGJ',
    idcal: 'R288',
  },
  {
    city: 'Valparaíso',
    idcalOld: '289',
    dataInstance: '2021/03/30',
    dir: 'vía Zoom Prodemu Valparaíso',
    colaborator: 'Prodemu Valparaíso',
    uuid: 'zWaGRMincQTe1syM7iJL',
    idcal: 'R289',
  },
  {
    city: 'San Felipe',
    idcalOld: '290',
    dataInstance: '2021/04/06',
    dir: 'vía Zoom Prodemu San Felipe',
    colaborator: 'Prodemu San Felipe',
    uuid: 'EdOeDs54ipSnFmAQhTsR',
    idcal: 'R290',
  },
  {
    city: 'Quillota',
    idcalOld: '291',
    dataInstance: '2021/04/20',
    dir: 'vía Zoom Prodemu Quillota',
    colaborator: 'Prodemu Quillota',
    uuid: 'IrKjmbz8r4uo96wdjo2q',
    idcal: 'R291',
  },
  {
    city: 'Petorca',
    idcalOld: '292',
    dataInstance: '2021/05/25',
    dir: 'via Zoom Prodemu Petorca',
    colaborator: 'Prodemu Petorca',
    uuid: 'KIsAsj0yi7SkUDi4A2oW',
    idcal: 'R292',
  },
  {
    city: 'Petorca',
    idcalOld: '293',
    dataInstance: '2021/06/15',
    dir: 'via Zoom Prodemu Petorca',
    colaborator: 'Prodemu Petorca',
    uuid: '2Cv5uWKxbAEUtrrO35lZ',
    idcal: 'R293',
  },
  {
    city: 'La Cruz',
    idcalOld: '294',
    dataInstance: '2021/06/17',
    dir: 'Colegio María Alonso Chacón, Calle Simpson No 18',
    colaborator: 'Municipalidad de La Cruz',
    uuid: 'ypdOuJju8dK5VzKDNhJ9',
    idcal: 'R294',
  },
  {
    city: 'Villa Alemana',
    idcalOld: '296',
    dataInstance: '2021/06/21',
    dir: 'via Zoom IM Villa Alemana',
    colaborator: 'Municipalidad de Villa Alemana',
    uuid: 'bwaSrYWoqY31kCOIYWIR',
    idcal: 'R296',
  },
  {
    city: 'Algarrobo',
    idcalOld: '295',
    dataInstance: '2021/06/22',
    dir: 'via Zoom',
    colaborator: 'Municipalidad de Algarrobo',
    uuid: '6X1ID9Yzt9f3zrX4AvtO',
    idcal: 'R295',
  },
  {
    city: 'Villa Alemana',
    idcalOld: '297',
    dataInstance: '2021/06/24',
    dir: 'vía Zoom',
    colaborator: 'Municipalidad de Villa Alemana',
    uuid: 'NGCmBVCA8I4uxI9AkqhS',
    idcal: 'R297',
  },
];

export const Operations = () => {
  //const [benef, setBenef] = React.useState<IBeneficiary[]>([]);

  const onClickFixBenef = async () => {
    await fetchBenefToFix();
  };

  //firebase:fetch 🔥🔥🔥
  const fetchBenefToFix = async () => {
    const year = 2019;
    const iniSearch = new Date(`${year}/01/01`);
    const endSearch = new Date(`${year}/12/31`);
    const ref = db
      .collection(`${dbKey.act}/${dbKey.uid}/${dbKey.cvn}`)
      .where('dateUpdate', '>=', iniSearch)
      .where('dateUpdate', '<=', endSearch)
      .withConverter(iBeneficiaryConverter);

    const queries = await ref.get();
    const list: IBeneficiary[] = queries.docs.map((doc) => doc.data());
    console.log('number of benefits: ', list.length);
    return list;
  };

  //firebase:push room date🔥🔥🔥
  const pushRoomDates = async () => {
    const ref = db.collection(`${dbKey.act}/${dbKey.uid}/${dbKey.room}`);
    //const roomToFixCut = [roomsToFix[0], roomsToFix[1]];

    roomsToFix.forEach(async (roomOld) => {
      //data format
      const dateToFix = new Date(roomOld.dataInstance);
      // data selectors
      const dir = roomOld.dir.split(',');
      let address = '';
      let nameAddress = '';
      switch (dir.length) {
        case 3: {
          nameAddress = dir[0];
          address = dir[1] + dir[2];
          break;
        }
        case 2: {
          nameAddress = dir[0];
          address = dir[1];
          break;
        }
        default: {
          nameAddress = dir[0];
          address = dir[0];
        }
      }
      dateToFix.setHours(15);

      const dataUpdate = {
        placeActivity: {
          date: dateToFix,
          dir: address,
          name: nameAddress,
        },
        placeDispatch: {
          date: dateToFix,
          dir: address,
          name: nameAddress,
        },
        dateInstance: dateToFix,
      };
      await ref.doc(roomOld.uuid).set(dataUpdate, { merge: true });
      console.log('room date update', roomOld.uuid);
    });
  };

  const eraseDuplicatedUUID = async () => {
    const year = 2019;
    const iniSearch = new Date(`${year}/01/01`);
    const endSearch = new Date(`${year}/12/31`);
    const ref = db
      .collection(`${dbKey.act}/${dbKey.uid}/${dbKey.room}`)
      .where('dateInstance', '>=', iniSearch)
      .where('dateInstance', '<=', endSearch)
      .withConverter(iClassroomConverter);
    //const roomToFixCut = [roomsToFix[0], roomsToFix[1]];
    const queries = await ref.get();
    const list = queries.docs.map((data) => data.data());

    const rif = db.collection(`${dbKey.act}/${dbKey.uid}/${dbKey.room}`);

    list.forEach(async (room) => {
      const attendees = room.attendees;
      const unique = new Set(attendees);
      const list: string[] = Array.from(unique);
      await rif.doc(room.uuid).set({ attendees: list, enrolled: list }, { merge: true });
      console.log(
        'duplicate erased in',
        room.idCal,
        '♻️',
        room.attendees.length,
        '->',
        list.length
      );
    });
  };

  return (
    <>
      <h4>performance data fix</h4>
      <p>arreglar beneficiaros con fechas mayor a 1/1/2022 </p>
      <button type='submit' className='' onClick={() => onClickFixBenef()} disabled>
        fix
      </button>
      <p>arreglar fechas actividades </p>
      <button type='submit' className='' onClick={() => pushRoomDates()} disabled>
        fix
      </button>
      <p>borrar room con attendees duplicados </p>
      <button type='submit' className='' onClick={() => eraseDuplicatedUUID()}>
        fix
      </button>
    </>
  );
};
