export interface City {
  regionId: string;
  region: string;
  provinceId: string;
  province: string;
  cityId: string;
  city: string;
}

export const cities: City[] = [
  {
    regionId: '01',
    region: 'Tarapacá',
    provinceId: '011',
    province: 'Iquique',
    cityId: '01101',
    city: 'Iquique',
  },
  {
    regionId: '01',
    region: 'Tarapacá',
    provinceId: '011',
    province: 'Iquique',
    cityId: '01107',
    city: 'Alto Hospicio',
  },
  {
    regionId: '01',
    region: 'Tarapacá',
    provinceId: '014',
    province: 'Tamarugal',
    cityId: '01401',
    city: 'Pozo Almonte',
  },
  {
    regionId: '01',
    region: 'Tarapacá',
    provinceId: '014',
    province: 'Tamarugal',
    cityId: '01402',
    city: 'Camiña',
  },
  {
    regionId: '01',
    region: 'Tarapacá',
    provinceId: '014',
    province: 'Tamarugal',
    cityId: '01403',
    city: 'Colchane',
  },
  {
    regionId: '01',
    region: 'Tarapacá',
    provinceId: '014',
    province: 'Tamarugal',
    cityId: '01404',
    city: 'Huara',
  },
  {
    regionId: '01',
    region: 'Tarapacá',
    provinceId: '014',
    province: 'Tamarugal',
    cityId: '01405',
    city: 'Pica',
  },
  {
    regionId: '02',
    region: 'Antofagasta',
    provinceId: '021',
    province: 'Antofagasta',
    cityId: '02101',
    city: 'Antofagasta',
  },
  {
    regionId: '02',
    region: 'Antofagasta',
    provinceId: '021',
    province: 'Antofagasta',
    cityId: '02102',
    city: 'Mejillones',
  },
  {
    regionId: '02',
    region: 'Antofagasta',
    provinceId: '021',
    province: 'Antofagasta',
    cityId: '02103',
    city: 'Sierra Gorda',
  },
  {
    regionId: '02',
    region: 'Antofagasta',
    provinceId: '021',
    province: 'Antofagasta',
    cityId: '02104',
    city: 'Taltal',
  },
  {
    regionId: '02',
    region: 'Antofagasta',
    provinceId: '022',
    province: 'El Loa',
    cityId: '02201',
    city: 'Calama',
  },
  {
    regionId: '02',
    region: 'Antofagasta',
    provinceId: '022',
    province: 'El Loa',
    cityId: '02202',
    city: 'Ollagüe',
  },
  {
    regionId: '02',
    region: 'Antofagasta',
    provinceId: '022',
    province: 'El Loa',
    cityId: '02203',
    city: 'San Pedro de Atacama',
  },
  {
    regionId: '02',
    region: 'Antofagasta',
    provinceId: '023',
    province: 'Tocopilla',
    cityId: '02301',
    city: 'Tocopilla',
  },
  {
    regionId: '02',
    region: 'Antofagasta',
    provinceId: '023',
    province: 'Tocopilla',
    cityId: '02302',
    city: 'María Elena',
  },
  {
    regionId: '03',
    region: 'Atacama',
    provinceId: '031',
    province: 'Copiapó',
    cityId: '03101',
    city: 'Copiapó',
  },
  {
    regionId: '03',
    region: 'Atacama',
    provinceId: '031',
    province: 'Copiapó',
    cityId: '03102',
    city: 'Caldera',
  },
  {
    regionId: '03',
    region: 'Atacama',
    provinceId: '031',
    province: 'Copiapó',
    cityId: '03103',
    city: 'Tierra Amarilla',
  },
  {
    regionId: '03',
    region: 'Atacama',
    provinceId: '032',
    province: 'Chañaral',
    cityId: '03201',
    city: 'Chañaral',
  },
  {
    regionId: '03',
    region: 'Atacama',
    provinceId: '032',
    province: 'Chañaral',
    cityId: '03202',
    city: 'Diego de Almagro',
  },
  {
    regionId: '03',
    region: 'Atacama',
    provinceId: '033',
    province: 'Huasco',
    cityId: '03301',
    city: 'Vallenar',
  },
  {
    regionId: '03',
    region: 'Atacama',
    provinceId: '033',
    province: 'Huasco',
    cityId: '03302',
    city: 'Alto del Carmen',
  },
  {
    regionId: '03',
    region: 'Atacama',
    provinceId: '033',
    province: 'Huasco',
    cityId: '03303',
    city: 'Freirina',
  },
  {
    regionId: '03',
    region: 'Atacama',
    provinceId: '033',
    province: 'Huasco',
    cityId: '03304',
    city: 'Huasco',
  },
  {
    regionId: '04',
    region: 'Coquimbo',
    provinceId: '041',
    province: 'Elqui',
    cityId: '04101',
    city: 'La Serena',
  },
  {
    regionId: '04',
    region: 'Coquimbo',
    provinceId: '041',
    province: 'Elqui',
    cityId: '04102',
    city: 'Coquimbo',
  },
  {
    regionId: '04',
    region: 'Coquimbo',
    provinceId: '041',
    province: 'Elqui',
    cityId: '04103',
    city: 'Andacollo',
  },
  {
    regionId: '04',
    region: 'Coquimbo',
    provinceId: '041',
    province: 'Elqui',
    cityId: '04104',
    city: 'La Higuera',
  },
  {
    regionId: '04',
    region: 'Coquimbo',
    provinceId: '041',
    province: 'Elqui',
    cityId: '04105',
    city: 'Paiguano',
  },
  {
    regionId: '04',
    region: 'Coquimbo',
    provinceId: '041',
    province: 'Elqui',
    cityId: '04106',
    city: 'Vicuña',
  },
  {
    regionId: '04',
    region: 'Coquimbo',
    provinceId: '042',
    province: 'Choapa',
    cityId: '04201',
    city: 'Illapel',
  },
  {
    regionId: '04',
    region: 'Coquimbo',
    provinceId: '042',
    province: 'Choapa',
    cityId: '04202',
    city: 'Canela',
  },
  {
    regionId: '04',
    region: 'Coquimbo',
    provinceId: '042',
    province: 'Choapa',
    cityId: '04203',
    city: 'Los Vilos',
  },
  {
    regionId: '04',
    region: 'Coquimbo',
    provinceId: '042',
    province: 'Choapa',
    cityId: '04204',
    city: 'Salamanca',
  },
  {
    regionId: '04',
    region: 'Coquimbo',
    provinceId: '043',
    province: 'Limarí',
    cityId: '04301',
    city: 'Ovalle',
  },
  {
    regionId: '04',
    region: 'Coquimbo',
    provinceId: '043',
    province: 'Limarí',
    cityId: '04302',
    city: 'Combarbalá',
  },
  {
    regionId: '04',
    region: 'Coquimbo',
    provinceId: '043',
    province: 'Limarí',
    cityId: '04303',
    city: 'Monte Patria',
  },
  {
    regionId: '04',
    region: 'Coquimbo',
    provinceId: '043',
    province: 'Limarí',
    cityId: '04304',
    city: 'Punitaqui',
  },
  {
    regionId: '04',
    region: 'Coquimbo',
    provinceId: '043',
    province: 'Limarí',
    cityId: '04305',
    city: 'Río Hurtado',
  },
  {
    regionId: '05',
    region: 'Valparaíso',
    provinceId: '051',
    province: 'Valparaíso',
    cityId: '05101',
    city: 'Valparaíso',
  },
  {
    regionId: '05',
    region: 'Valparaíso',
    provinceId: '051',
    province: 'Valparaíso',
    cityId: '05102',
    city: 'Casablanca',
  },
  {
    regionId: '05',
    region: 'Valparaíso',
    provinceId: '051',
    province: 'Valparaíso',
    cityId: '05103',
    city: 'Concón',
  },
  {
    regionId: '05',
    region: 'Valparaíso',
    provinceId: '051',
    province: 'Valparaíso',
    cityId: '05104',
    city: 'Juan Fernández',
  },
  {
    regionId: '05',
    region: 'Valparaíso',
    provinceId: '051',
    province: 'Valparaíso',
    cityId: '05105',
    city: 'Puchuncaví',
  },
  {
    regionId: '05',
    region: 'Valparaíso',
    provinceId: '051',
    province: 'Valparaíso',
    cityId: '05107',
    city: 'Quintero',
  },
  {
    regionId: '05',
    region: 'Valparaíso',
    provinceId: '051',
    province: 'Valparaíso',
    cityId: '05109',
    city: 'Viña del Mar',
  },
  {
    regionId: '05',
    region: 'Valparaíso',
    provinceId: '052',
    province: 'Isla de Pascua',
    cityId: '05201',
    city: 'Isla de Pascua',
  },
  {
    regionId: '05',
    region: 'Valparaíso',
    provinceId: '053',
    province: 'Los Andes',
    cityId: '05301',
    city: 'Los Andes',
  },
  {
    regionId: '05',
    region: 'Valparaíso',
    provinceId: '053',
    province: 'Los Andes',
    cityId: '05302',
    city: 'Calle Larga',
  },
  {
    regionId: '05',
    region: 'Valparaíso',
    provinceId: '053',
    province: 'Los Andes',
    cityId: '05303',
    city: 'Rinconada',
  },
  {
    regionId: '05',
    region: 'Valparaíso',
    provinceId: '053',
    province: 'Los Andes',
    cityId: '05304',
    city: 'San Esteban',
  },
  {
    regionId: '05',
    region: 'Valparaíso',
    provinceId: '054',
    province: 'Petorca',
    cityId: '05401',
    city: 'La Ligua',
  },
  {
    regionId: '05',
    region: 'Valparaíso',
    provinceId: '054',
    province: 'Petorca',
    cityId: '05402',
    city: 'Cabildo',
  },
  {
    regionId: '05',
    region: 'Valparaíso',
    provinceId: '054',
    province: 'Petorca',
    cityId: '05403',
    city: 'Papudo',
  },
  {
    regionId: '05',
    region: 'Valparaíso',
    provinceId: '054',
    province: 'Petorca',
    cityId: '05404',
    city: 'Petorca',
  },
  {
    regionId: '05',
    region: 'Valparaíso',
    provinceId: '054',
    province: 'Petorca',
    cityId: '05405',
    city: 'Zapallar',
  },
  {
    regionId: '05',
    region: 'Valparaíso',
    provinceId: '055',
    province: 'Quillota',
    cityId: '05501',
    city: 'Quillota',
  },
  {
    regionId: '05',
    region: 'Valparaíso',
    provinceId: '055',
    province: 'Quillota',
    cityId: '05502',
    city: 'Calera',
  },
  {
    regionId: '05',
    region: 'Valparaíso',
    provinceId: '055',
    province: 'Quillota',
    cityId: '05503',
    city: 'Hijuelas',
  },
  {
    regionId: '05',
    region: 'Valparaíso',
    provinceId: '055',
    province: 'Quillota',
    cityId: '05504',
    city: 'La Cruz',
  },
  {
    regionId: '05',
    region: 'Valparaíso',
    provinceId: '055',
    province: 'Quillota',
    cityId: '05506',
    city: 'Nogales',
  },
  {
    regionId: '05',
    region: 'Valparaíso',
    provinceId: '056',
    province: 'San Antonio',
    cityId: '05601',
    city: 'San Antonio',
  },
  {
    regionId: '05',
    region: 'Valparaíso',
    provinceId: '056',
    province: 'San Antonio',
    cityId: '05602',
    city: 'Algarrobo',
  },
  {
    regionId: '05',
    region: 'Valparaíso',
    provinceId: '056',
    province: 'San Antonio',
    cityId: '05603',
    city: 'Cartagena',
  },
  {
    regionId: '05',
    region: 'Valparaíso',
    provinceId: '056',
    province: 'San Antonio',
    cityId: '05604',
    city: 'El Quisco',
  },
  {
    regionId: '05',
    region: 'Valparaíso',
    provinceId: '056',
    province: 'San Antonio',
    cityId: '05605',
    city: 'El Tabo',
  },
  {
    regionId: '05',
    region: 'Valparaíso',
    provinceId: '056',
    province: 'San Antonio',
    cityId: '05606',
    city: 'Santo Domingo',
  },
  {
    regionId: '05',
    region: 'Valparaíso',
    provinceId: '057',
    province: 'San Felipe de Aconcagua',
    cityId: '05701',
    city: 'San Felipe',
  },
  {
    regionId: '05',
    region: 'Valparaíso',
    provinceId: '057',
    province: 'San Felipe de Aconcagua',
    cityId: '05702',
    city: 'Catemu',
  },
  {
    regionId: '05',
    region: 'Valparaíso',
    provinceId: '057',
    province: 'San Felipe de Aconcagua',
    cityId: '05703',
    city: 'Llaillay',
  },
  {
    regionId: '05',
    region: 'Valparaíso',
    provinceId: '057',
    province: 'San Felipe de Aconcagua',
    cityId: '05704',
    city: 'Panquehue',
  },
  {
    regionId: '05',
    region: 'Valparaíso',
    provinceId: '057',
    province: 'San Felipe de Aconcagua',
    cityId: '05705',
    city: 'Putaendo',
  },
  {
    regionId: '05',
    region: 'Valparaíso',
    provinceId: '057',
    province: 'San Felipe de Aconcagua',
    cityId: '05706',
    city: 'Santa María',
  },
  {
    regionId: '05',
    region: 'Valparaíso',
    provinceId: '058',
    province: 'Marga Marga',
    cityId: '05801',
    city: 'Quilpué',
  },
  {
    regionId: '05',
    region: 'Valparaíso',
    provinceId: '058',
    province: 'Marga Marga',
    cityId: '05802',
    city: 'Limache',
  },
  {
    regionId: '05',
    region: 'Valparaíso',
    provinceId: '058',
    province: 'Marga Marga',
    cityId: '05803',
    city: 'Olmué',
  },
  {
    regionId: '05',
    region: 'Valparaíso',
    provinceId: '058',
    province: 'Marga Marga',
    cityId: '05804',
    city: 'Villa Alemana',
  },
  {
    regionId: '06',
    region: "Libertador General Bernardo O'Higgins",
    provinceId: '061',
    province: 'Cachapoal',
    cityId: '06101',
    city: 'Rancagua',
  },
  {
    regionId: '06',
    region: "Libertador General Bernardo O'Higgins",
    provinceId: '061',
    province: 'Cachapoal',
    cityId: '06102',
    city: 'Codegua',
  },
  {
    regionId: '06',
    region: "Libertador General Bernardo O'Higgins",
    provinceId: '061',
    province: 'Cachapoal',
    cityId: '06103',
    city: 'Coinco',
  },
  {
    regionId: '06',
    region: "Libertador General Bernardo O'Higgins",
    provinceId: '061',
    province: 'Cachapoal',
    cityId: '06104',
    city: 'Coltauco',
  },
  {
    regionId: '06',
    region: "Libertador General Bernardo O'Higgins",
    provinceId: '061',
    province: 'Cachapoal',
    cityId: '06105',
    city: 'Doñihue',
  },
  {
    regionId: '06',
    region: "Libertador General Bernardo O'Higgins",
    provinceId: '061',
    province: 'Cachapoal',
    cityId: '06106',
    city: 'Graneros',
  },
  {
    regionId: '06',
    region: "Libertador General Bernardo O'Higgins",
    provinceId: '061',
    province: 'Cachapoal',
    cityId: '06107',
    city: 'Las Cabras',
  },
  {
    regionId: '06',
    region: "Libertador General Bernardo O'Higgins",
    provinceId: '061',
    province: 'Cachapoal',
    cityId: '06108',
    city: 'Machalí',
  },
  {
    regionId: '06',
    region: "Libertador General Bernardo O'Higgins",
    provinceId: '061',
    province: 'Cachapoal',
    cityId: '06109',
    city: 'Malloa',
  },
  {
    regionId: '06',
    region: "Libertador General Bernardo O'Higgins",
    provinceId: '061',
    province: 'Cachapoal',
    cityId: '06110',
    city: 'Mostazal',
  },
  {
    regionId: '06',
    region: "Libertador General Bernardo O'Higgins",
    provinceId: '061',
    province: 'Cachapoal',
    cityId: '06111',
    city: 'Olivar',
  },
  {
    regionId: '06',
    region: "Libertador General Bernardo O'Higgins",
    provinceId: '061',
    province: 'Cachapoal',
    cityId: '06112',
    city: 'Peumo',
  },
  {
    regionId: '06',
    region: "Libertador General Bernardo O'Higgins",
    provinceId: '061',
    province: 'Cachapoal',
    cityId: '06113',
    city: 'Pichidegua',
  },
  {
    regionId: '06',
    region: "Libertador General Bernardo O'Higgins",
    provinceId: '061',
    province: 'Cachapoal',
    cityId: '06114',
    city: 'Quinta de Tilcoco',
  },
  {
    regionId: '06',
    region: "Libertador General Bernardo O'Higgins",
    provinceId: '061',
    province: 'Cachapoal',
    cityId: '06115',
    city: 'Rengo',
  },
  {
    regionId: '06',
    region: "Libertador General Bernardo O'Higgins",
    provinceId: '061',
    province: 'Cachapoal',
    cityId: '06116',
    city: 'Requínoa',
  },
  {
    regionId: '06',
    region: "Libertador General Bernardo O'Higgins",
    provinceId: '061',
    province: 'Cachapoal',
    cityId: '06117',
    city: 'San Vicente',
  },
  {
    regionId: '06',
    region: "Libertador General Bernardo O'Higgins",
    provinceId: '062',
    province: 'Cardenal Caro',
    cityId: '06201',
    city: 'Pichilemu',
  },
  {
    regionId: '06',
    region: "Libertador General Bernardo O'Higgins",
    provinceId: '062',
    province: 'Cardenal Caro',
    cityId: '06202',
    city: 'La Estrella',
  },
  {
    regionId: '06',
    region: "Libertador General Bernardo O'Higgins",
    provinceId: '062',
    province: 'Cardenal Caro',
    cityId: '06203',
    city: 'Litueche',
  },
  {
    regionId: '06',
    region: "Libertador General Bernardo O'Higgins",
    provinceId: '062',
    province: 'Cardenal Caro',
    cityId: '06204',
    city: 'Marchihue',
  },
  {
    regionId: '06',
    region: "Libertador General Bernardo O'Higgins",
    provinceId: '062',
    province: 'Cardenal Caro',
    cityId: '06205',
    city: 'Navidad',
  },
  {
    regionId: '06',
    region: "Libertador General Bernardo O'Higgins",
    provinceId: '062',
    province: 'Cardenal Caro',
    cityId: '06206',
    city: 'Paredones',
  },
  {
    regionId: '06',
    region: "Libertador General Bernardo O'Higgins",
    provinceId: '063',
    province: 'Colchagua',
    cityId: '06301',
    city: 'San Fernando',
  },
  {
    regionId: '06',
    region: "Libertador General Bernardo O'Higgins",
    provinceId: '063',
    province: 'Colchagua',
    cityId: '06302',
    city: 'Chépica',
  },
  {
    regionId: '06',
    region: "Libertador General Bernardo O'Higgins",
    provinceId: '063',
    province: 'Colchagua',
    cityId: '06303',
    city: 'Chimbarongo',
  },
  {
    regionId: '06',
    region: "Libertador General Bernardo O'Higgins",
    provinceId: '063',
    province: 'Colchagua',
    cityId: '06304',
    city: 'Lolol',
  },
  {
    regionId: '06',
    region: "Libertador General Bernardo O'Higgins",
    provinceId: '063',
    province: 'Colchagua',
    cityId: '06305',
    city: 'Nancagua',
  },
  {
    regionId: '06',
    region: "Libertador General Bernardo O'Higgins",
    provinceId: '063',
    province: 'Colchagua',
    cityId: '06306',
    city: 'Palmilla',
  },
  {
    regionId: '06',
    region: "Libertador General Bernardo O'Higgins",
    provinceId: '063',
    province: 'Colchagua',
    cityId: '06307',
    city: 'Peralillo',
  },
  {
    regionId: '06',
    region: "Libertador General Bernardo O'Higgins",
    provinceId: '063',
    province: 'Colchagua',
    cityId: '06308',
    city: 'Placilla',
  },
  {
    regionId: '06',
    region: "Libertador General Bernardo O'Higgins",
    provinceId: '063',
    province: 'Colchagua',
    cityId: '06309',
    city: 'Pumanque',
  },
  {
    regionId: '06',
    region: "Libertador General Bernardo O'Higgins",
    provinceId: '063',
    province: 'Colchagua',
    cityId: '06310',
    city: 'Santa Cruz',
  },
  {
    regionId: '07',
    region: 'Maule',
    provinceId: '071',
    province: 'Talca',
    cityId: '07101',
    city: 'Talca',
  },
  {
    regionId: '07',
    region: 'Maule',
    provinceId: '071',
    province: 'Talca',
    cityId: '07102',
    city: 'Constitución',
  },
  {
    regionId: '07',
    region: 'Maule',
    provinceId: '071',
    province: 'Talca',
    cityId: '07103',
    city: 'Curepto',
  },
  {
    regionId: '07',
    region: 'Maule',
    provinceId: '071',
    province: 'Talca',
    cityId: '07104',
    city: 'Empedrado',
  },
  {
    regionId: '07',
    region: 'Maule',
    provinceId: '071',
    province: 'Talca',
    cityId: '07105',
    city: 'Maule',
  },
  {
    regionId: '07',
    region: 'Maule',
    provinceId: '071',
    province: 'Talca',
    cityId: '07106',
    city: 'Pelarco',
  },
  {
    regionId: '07',
    region: 'Maule',
    provinceId: '071',
    province: 'Talca',
    cityId: '07107',
    city: 'Pencahue',
  },
  {
    regionId: '07',
    region: 'Maule',
    provinceId: '071',
    province: 'Talca',
    cityId: '07108',
    city: 'Río Claro',
  },
  {
    regionId: '07',
    region: 'Maule',
    provinceId: '071',
    province: 'Talca',
    cityId: '07109',
    city: 'San Clemente',
  },
  {
    regionId: '07',
    region: 'Maule',
    provinceId: '071',
    province: 'Talca',
    cityId: '07110',
    city: 'San Rafael',
  },
  {
    regionId: '07',
    region: 'Maule',
    provinceId: '072',
    province: 'Cauquenes',
    cityId: '07201',
    city: 'Cauquenes',
  },
  {
    regionId: '07',
    region: 'Maule',
    provinceId: '072',
    province: 'Cauquenes',
    cityId: '07202',
    city: 'Chanco',
  },
  {
    regionId: '07',
    region: 'Maule',
    provinceId: '072',
    province: 'Cauquenes',
    cityId: '07203',
    city: 'Pelluhue',
  },
  {
    regionId: '07',
    region: 'Maule',
    provinceId: '073',
    province: 'Curicó',
    cityId: '07301',
    city: 'Curicó',
  },
  {
    regionId: '07',
    region: 'Maule',
    provinceId: '073',
    province: 'Curicó',
    cityId: '07302',
    city: 'Hualañé',
  },
  {
    regionId: '07',
    region: 'Maule',
    provinceId: '073',
    province: 'Curicó',
    cityId: '07303',
    city: 'Licantén',
  },
  {
    regionId: '07',
    region: 'Maule',
    provinceId: '073',
    province: 'Curicó',
    cityId: '07304',
    city: 'Molina',
  },
  {
    regionId: '07',
    region: 'Maule',
    provinceId: '073',
    province: 'Curicó',
    cityId: '07305',
    city: 'Rauco',
  },
  {
    regionId: '07',
    region: 'Maule',
    provinceId: '073',
    province: 'Curicó',
    cityId: '07306',
    city: 'Romeral',
  },
  {
    regionId: '07',
    region: 'Maule',
    provinceId: '073',
    province: 'Curicó',
    cityId: '07307',
    city: 'Sagrada Familia',
  },
  {
    regionId: '07',
    region: 'Maule',
    provinceId: '073',
    province: 'Curicó',
    cityId: '07308',
    city: 'Teno',
  },
  {
    regionId: '07',
    region: 'Maule',
    provinceId: '073',
    province: 'Curicó',
    cityId: '07309',
    city: 'Vichuquén',
  },
  {
    regionId: '07',
    region: 'Maule',
    provinceId: '074',
    province: 'Linares',
    cityId: '07401',
    city: 'Linares',
  },
  {
    regionId: '07',
    region: 'Maule',
    provinceId: '074',
    province: 'Linares',
    cityId: '07402',
    city: 'Colbún',
  },
  {
    regionId: '07',
    region: 'Maule',
    provinceId: '074',
    province: 'Linares',
    cityId: '07403',
    city: 'Longaví',
  },
  {
    regionId: '07',
    region: 'Maule',
    provinceId: '074',
    province: 'Linares',
    cityId: '07404',
    city: 'Parral',
  },
  {
    regionId: '07',
    region: 'Maule',
    provinceId: '074',
    province: 'Linares',
    cityId: '07405',
    city: 'Retiro',
  },
  {
    regionId: '07',
    region: 'Maule',
    provinceId: '074',
    province: 'Linares',
    cityId: '07406',
    city: 'San Javier',
  },
  {
    regionId: '07',
    region: 'Maule',
    provinceId: '074',
    province: 'Linares',
    cityId: '07407',
    city: 'Villa Alegre',
  },
  {
    regionId: '07',
    region: 'Maule',
    provinceId: '074',
    province: 'Linares',
    cityId: '07408',
    city: 'Yerbas Buenas',
  },
  {
    regionId: '08',
    region: 'Biobío',
    provinceId: '081',
    province: 'Concepción',
    cityId: '08101',
    city: 'Concepción',
  },
  {
    regionId: '08',
    region: 'Biobío',
    provinceId: '081',
    province: 'Concepción',
    cityId: '08102',
    city: 'Coronel',
  },
  {
    regionId: '08',
    region: 'Biobío',
    provinceId: '081',
    province: 'Concepción',
    cityId: '08103',
    city: 'Chiguayante',
  },
  {
    regionId: '08',
    region: 'Biobío',
    provinceId: '081',
    province: 'Concepción',
    cityId: '08104',
    city: 'Florida',
  },
  {
    regionId: '08',
    region: 'Biobío',
    provinceId: '081',
    province: 'Concepción',
    cityId: '08105',
    city: 'Hualqui',
  },
  {
    regionId: '08',
    region: 'Biobío',
    provinceId: '081',
    province: 'Concepción',
    cityId: '08106',
    city: 'Lota',
  },
  {
    regionId: '08',
    region: 'Biobío',
    provinceId: '081',
    province: 'Concepción',
    cityId: '08107',
    city: 'Penco',
  },
  {
    regionId: '08',
    region: 'Biobío',
    provinceId: '081',
    province: 'Concepción',
    cityId: '08108',
    city: 'San Pedro de la Paz',
  },
  {
    regionId: '08',
    region: 'Biobío',
    provinceId: '081',
    province: 'Concepción',
    cityId: '08109',
    city: 'Santa Juana',
  },
  {
    regionId: '08',
    region: 'Biobío',
    provinceId: '081',
    province: 'Concepción',
    cityId: '08110',
    city: 'Talcahuano',
  },
  {
    regionId: '08',
    region: 'Biobío',
    provinceId: '081',
    province: 'Concepción',
    cityId: '08111',
    city: 'Tomé',
  },
  {
    regionId: '08',
    region: 'Biobío',
    provinceId: '081',
    province: 'Concepción',
    cityId: '08112',
    city: 'Hualpén',
  },
  {
    regionId: '08',
    region: 'Biobío',
    provinceId: '082',
    province: 'Arauco',
    cityId: '08201',
    city: 'Lebu',
  },
  {
    regionId: '08',
    region: 'Biobío',
    provinceId: '082',
    province: 'Arauco',
    cityId: '08202',
    city: 'Arauco',
  },
  {
    regionId: '08',
    region: 'Biobío',
    provinceId: '082',
    province: 'Arauco',
    cityId: '08203',
    city: 'Cañete',
  },
  {
    regionId: '08',
    region: 'Biobío',
    provinceId: '082',
    province: 'Arauco',
    cityId: '08204',
    city: 'Contulmo',
  },
  {
    regionId: '08',
    region: 'Biobío',
    provinceId: '082',
    province: 'Arauco',
    cityId: '08205',
    city: 'Curanilahue',
  },
  {
    regionId: '08',
    region: 'Biobío',
    provinceId: '082',
    province: 'Arauco',
    cityId: '08206',
    city: 'Los Alamos',
  },
  {
    regionId: '08',
    region: 'Biobío',
    provinceId: '082',
    province: 'Arauco',
    cityId: '08207',
    city: 'Tirúa',
  },
  {
    regionId: '08',
    region: 'Biobío',
    provinceId: '083',
    province: 'Biobío',
    cityId: '08301',
    city: 'Los Angeles',
  },
  {
    regionId: '08',
    region: 'Biobío',
    provinceId: '083',
    province: 'Biobío',
    cityId: '08302',
    city: 'Antuco',
  },
  {
    regionId: '08',
    region: 'Biobío',
    provinceId: '083',
    province: 'Biobío',
    cityId: '08303',
    city: 'Cabrero',
  },
  {
    regionId: '08',
    region: 'Biobío',
    provinceId: '083',
    province: 'Biobío',
    cityId: '08304',
    city: 'Laja',
  },
  {
    regionId: '08',
    region: 'Biobío',
    provinceId: '083',
    province: 'Biobío',
    cityId: '08305',
    city: 'Mulchén',
  },
  {
    regionId: '08',
    region: 'Biobío',
    provinceId: '083',
    province: 'Biobío',
    cityId: '08306',
    city: 'Nacimiento',
  },
  {
    regionId: '08',
    region: 'Biobío',
    provinceId: '083',
    province: 'Biobío',
    cityId: '08307',
    city: 'Negrete',
  },
  {
    regionId: '08',
    region: 'Biobío',
    provinceId: '083',
    province: 'Biobío',
    cityId: '08308',
    city: 'Quilaco',
  },
  {
    regionId: '08',
    region: 'Biobío',
    provinceId: '083',
    province: 'Biobío',
    cityId: '08309',
    city: 'Quilleco',
  },
  {
    regionId: '08',
    region: 'Biobío',
    provinceId: '083',
    province: 'Biobío',
    cityId: '08310',
    city: 'San Rosendo',
  },
  {
    regionId: '08',
    region: 'Biobío',
    provinceId: '083',
    province: 'Biobío',
    cityId: '08311',
    city: 'Santa Bárbara',
  },
  {
    regionId: '08',
    region: 'Biobío',
    provinceId: '083',
    province: 'Biobío',
    cityId: '08312',
    city: 'Tucapel',
  },
  {
    regionId: '08',
    region: 'Biobío',
    provinceId: '083',
    province: 'Biobío',
    cityId: '08313',
    city: 'Yumbel',
  },
  {
    regionId: '08',
    region: 'Biobío',
    provinceId: '083',
    province: 'Biobío',
    cityId: '08314',
    city: 'Alto Biobío',
  },
  {
    regionId: '09',
    region: 'La Araucanía',
    provinceId: '091',
    province: 'Cautín',
    cityId: '09101',
    city: 'Temuco',
  },
  {
    regionId: '09',
    region: 'La Araucanía',
    provinceId: '091',
    province: 'Cautín',
    cityId: '09102',
    city: 'Carahue',
  },
  {
    regionId: '09',
    region: 'La Araucanía',
    provinceId: '091',
    province: 'Cautín',
    cityId: '09103',
    city: 'Cunco',
  },
  {
    regionId: '09',
    region: 'La Araucanía',
    provinceId: '091',
    province: 'Cautín',
    cityId: '09104',
    city: 'Curarrehue',
  },
  {
    regionId: '09',
    region: 'La Araucanía',
    provinceId: '091',
    province: 'Cautín',
    cityId: '09105',
    city: 'Freire',
  },
  {
    regionId: '09',
    region: 'La Araucanía',
    provinceId: '091',
    province: 'Cautín',
    cityId: '09106',
    city: 'Galvarino',
  },
  {
    regionId: '09',
    region: 'La Araucanía',
    provinceId: '091',
    province: 'Cautín',
    cityId: '09107',
    city: 'Gorbea',
  },
  {
    regionId: '09',
    region: 'La Araucanía',
    provinceId: '091',
    province: 'Cautín',
    cityId: '09108',
    city: 'Lautaro',
  },
  {
    regionId: '09',
    region: 'La Araucanía',
    provinceId: '091',
    province: 'Cautín',
    cityId: '09109',
    city: 'Loncoche',
  },
  {
    regionId: '09',
    region: 'La Araucanía',
    provinceId: '091',
    province: 'Cautín',
    cityId: '09110',
    city: 'Melipeuco',
  },
  {
    regionId: '09',
    region: 'La Araucanía',
    provinceId: '091',
    province: 'Cautín',
    cityId: '09111',
    city: 'Nueva Imperial',
  },
  {
    regionId: '09',
    region: 'La Araucanía',
    provinceId: '091',
    province: 'Cautín',
    cityId: '09112',
    city: 'Padre Las Casas',
  },
  {
    regionId: '09',
    region: 'La Araucanía',
    provinceId: '091',
    province: 'Cautín',
    cityId: '09113',
    city: 'Perquenco',
  },
  {
    regionId: '09',
    region: 'La Araucanía',
    provinceId: '091',
    province: 'Cautín',
    cityId: '09114',
    city: 'Pitrufquén',
  },
  {
    regionId: '09',
    region: 'La Araucanía',
    provinceId: '091',
    province: 'Cautín',
    cityId: '09115',
    city: 'Pucón',
  },
  {
    regionId: '09',
    region: 'La Araucanía',
    provinceId: '091',
    province: 'Cautín',
    cityId: '09116',
    city: 'Saavedra',
  },
  {
    regionId: '09',
    region: 'La Araucanía',
    provinceId: '091',
    province: 'Cautín',
    cityId: '09117',
    city: 'Teodoro Schmidt',
  },
  {
    regionId: '09',
    region: 'La Araucanía',
    provinceId: '091',
    province: 'Cautín',
    cityId: '09118',
    city: 'Toltén',
  },
  {
    regionId: '09',
    region: 'La Araucanía',
    provinceId: '091',
    province: 'Cautín',
    cityId: '09119',
    city: 'Vilcún',
  },
  {
    regionId: '09',
    region: 'La Araucanía',
    provinceId: '091',
    province: 'Cautín',
    cityId: '09120',
    city: 'Villarrica',
  },
  {
    regionId: '09',
    region: 'La Araucanía',
    provinceId: '091',
    province: 'Cautín',
    cityId: '09121',
    city: 'Cholchol',
  },
  {
    regionId: '09',
    region: 'La Araucanía',
    provinceId: '092',
    province: 'Malleco',
    cityId: '09201',
    city: 'Angol',
  },
  {
    regionId: '09',
    region: 'La Araucanía',
    provinceId: '092',
    province: 'Malleco',
    cityId: '09202',
    city: 'Collipulli',
  },
  {
    regionId: '09',
    region: 'La Araucanía',
    provinceId: '092',
    province: 'Malleco',
    cityId: '09203',
    city: 'Curacautín',
  },
  {
    regionId: '09',
    region: 'La Araucanía',
    provinceId: '092',
    province: 'Malleco',
    cityId: '09204',
    city: 'Ercilla',
  },
  {
    regionId: '09',
    region: 'La Araucanía',
    provinceId: '092',
    province: 'Malleco',
    cityId: '09205',
    city: 'Lonquimay',
  },
  {
    regionId: '09',
    region: 'La Araucanía',
    provinceId: '092',
    province: 'Malleco',
    cityId: '09206',
    city: 'Los Sauces',
  },
  {
    regionId: '09',
    region: 'La Araucanía',
    provinceId: '092',
    province: 'Malleco',
    cityId: '09207',
    city: 'Lumaco',
  },
  {
    regionId: '09',
    region: 'La Araucanía',
    provinceId: '092',
    province: 'Malleco',
    cityId: '09208',
    city: 'Purén',
  },
  {
    regionId: '09',
    region: 'La Araucanía',
    provinceId: '092',
    province: 'Malleco',
    cityId: '09209',
    city: 'Renaico',
  },
  {
    regionId: '09',
    region: 'La Araucanía',
    provinceId: '092',
    province: 'Malleco',
    cityId: '09210',
    city: 'Traiguén',
  },
  {
    regionId: '09',
    region: 'La Araucanía',
    provinceId: '092',
    province: 'Malleco',
    cityId: '09211',
    city: 'Victoria',
  },
  {
    regionId: '10',
    region: 'Los Lagos',
    provinceId: '101',
    province: 'Llanquihue',
    cityId: '10101',
    city: 'Puerto Montt',
  },
  {
    regionId: '10',
    region: 'Los Lagos',
    provinceId: '101',
    province: 'Llanquihue',
    cityId: '10102',
    city: 'Calbuco',
  },
  {
    regionId: '10',
    region: 'Los Lagos',
    provinceId: '101',
    province: 'Llanquihue',
    cityId: '10103',
    city: 'Cochamó',
  },
  {
    regionId: '10',
    region: 'Los Lagos',
    provinceId: '101',
    province: 'Llanquihue',
    cityId: '10104',
    city: 'Fresia',
  },
  {
    regionId: '10',
    region: 'Los Lagos',
    provinceId: '101',
    province: 'Llanquihue',
    cityId: '10105',
    city: 'Frutillar',
  },
  {
    regionId: '10',
    region: 'Los Lagos',
    provinceId: '101',
    province: 'Llanquihue',
    cityId: '10106',
    city: 'Los Muermos',
  },
  {
    regionId: '10',
    region: 'Los Lagos',
    provinceId: '101',
    province: 'Llanquihue',
    cityId: '10107',
    city: 'Llanquihue',
  },
  {
    regionId: '10',
    region: 'Los Lagos',
    provinceId: '101',
    province: 'Llanquihue',
    cityId: '10108',
    city: 'Maullín',
  },
  {
    regionId: '10',
    region: 'Los Lagos',
    provinceId: '101',
    province: 'Llanquihue',
    cityId: '10109',
    city: 'Puerto Varas',
  },
  {
    regionId: '10',
    region: 'Los Lagos',
    provinceId: '102',
    province: 'Chiloé',
    cityId: '10201',
    city: 'Castro',
  },
  {
    regionId: '10',
    region: 'Los Lagos',
    provinceId: '102',
    province: 'Chiloé',
    cityId: '10202',
    city: 'Ancud',
  },
  {
    regionId: '10',
    region: 'Los Lagos',
    provinceId: '102',
    province: 'Chiloé',
    cityId: '10203',
    city: 'Chonchi',
  },
  {
    regionId: '10',
    region: 'Los Lagos',
    provinceId: '102',
    province: 'Chiloé',
    cityId: '10204',
    city: 'Curaco de Vélez',
  },
  {
    regionId: '10',
    region: 'Los Lagos',
    provinceId: '102',
    province: 'Chiloé',
    cityId: '10205',
    city: 'Dalcahue',
  },
  {
    regionId: '10',
    region: 'Los Lagos',
    provinceId: '102',
    province: 'Chiloé',
    cityId: '10206',
    city: 'Puqueldón',
  },
  {
    regionId: '10',
    region: 'Los Lagos',
    provinceId: '102',
    province: 'Chiloé',
    cityId: '10207',
    city: 'Queilén',
  },
  {
    regionId: '10',
    region: 'Los Lagos',
    provinceId: '102',
    province: 'Chiloé',
    cityId: '10208',
    city: 'Quellón',
  },
  {
    regionId: '10',
    region: 'Los Lagos',
    provinceId: '102',
    province: 'Chiloé',
    cityId: '10209',
    city: 'Quemchi',
  },
  {
    regionId: '10',
    region: 'Los Lagos',
    provinceId: '102',
    province: 'Chiloé',
    cityId: '10210',
    city: 'Quinchao',
  },
  {
    regionId: '10',
    region: 'Los Lagos',
    provinceId: '103',
    province: 'Osorno',
    cityId: '10301',
    city: 'Osorno',
  },
  {
    regionId: '10',
    region: 'Los Lagos',
    provinceId: '103',
    province: 'Osorno',
    cityId: '10302',
    city: 'Puerto Octay',
  },
  {
    regionId: '10',
    region: 'Los Lagos',
    provinceId: '103',
    province: 'Osorno',
    cityId: '10303',
    city: 'Purranque',
  },
  {
    regionId: '10',
    region: 'Los Lagos',
    provinceId: '103',
    province: 'Osorno',
    cityId: '10304',
    city: 'Puyehue',
  },
  {
    regionId: '10',
    region: 'Los Lagos',
    provinceId: '103',
    province: 'Osorno',
    cityId: '10305',
    city: 'Río Negro',
  },
  {
    regionId: '10',
    region: 'Los Lagos',
    provinceId: '103',
    province: 'Osorno',
    cityId: '10306',
    city: 'San Juan de la Costa',
  },
  {
    regionId: '10',
    region: 'Los Lagos',
    provinceId: '103',
    province: 'Osorno',
    cityId: '10307',
    city: 'San Pablo',
  },
  {
    regionId: '10',
    region: 'Los Lagos',
    provinceId: '104',
    province: 'Palena',
    cityId: '10401',
    city: 'Chaitén',
  },
  {
    regionId: '10',
    region: 'Los Lagos',
    provinceId: '104',
    province: 'Palena',
    cityId: '10402',
    city: 'Futaleufú',
  },
  {
    regionId: '10',
    region: 'Los Lagos',
    provinceId: '104',
    province: 'Palena',
    cityId: '10403',
    city: 'Hualaihué',
  },
  {
    regionId: '10',
    region: 'Los Lagos',
    provinceId: '104',
    province: 'Palena',
    cityId: '10404',
    city: 'Palena',
  },
  {
    regionId: '11',
    region: 'Aysén del General Carlos Ibáñez del Campo',
    provinceId: '111',
    province: 'Coihaique',
    cityId: '11101',
    city: 'Coihaique',
  },
  {
    regionId: '11',
    region: 'Aysén del General Carlos Ibáñez del Campo',
    provinceId: '111',
    province: 'Coihaique',
    cityId: '11102',
    city: 'Lago Verde',
  },
  {
    regionId: '11',
    region: 'Aysén del General Carlos Ibáñez del Campo',
    provinceId: '112',
    province: 'Aisén',
    cityId: '11201',
    city: 'Aisén',
  },
  {
    regionId: '11',
    region: 'Aysén del General Carlos Ibáñez del Campo',
    provinceId: '112',
    province: 'Aisén',
    cityId: '11202',
    city: 'Cisnes',
  },
  {
    regionId: '11',
    region: 'Aysén del General Carlos Ibáñez del Campo',
    provinceId: '112',
    province: 'Aisén',
    cityId: '11203',
    city: 'Guaitecas',
  },
  {
    regionId: '11',
    region: 'Aysén del General Carlos Ibáñez del Campo',
    provinceId: '113',
    province: 'Capitán Prat',
    cityId: '11301',
    city: 'Cochrane',
  },
  {
    regionId: '11',
    region: 'Aysén del General Carlos Ibáñez del Campo',
    provinceId: '113',
    province: 'Capitán Prat',
    cityId: '11302',
    city: "O'Higgins",
  },
  {
    regionId: '11',
    region: 'Aysén del General Carlos Ibáñez del Campo',
    provinceId: '113',
    province: 'Capitán Prat',
    cityId: '11303',
    city: 'Tortel',
  },
  {
    regionId: '11',
    region: 'Aysén del General Carlos Ibáñez del Campo',
    provinceId: '114',
    province: 'General Carrera',
    cityId: '11401',
    city: 'Chile Chico',
  },
  {
    regionId: '11',
    region: 'Aysén del General Carlos Ibáñez del Campo',
    provinceId: '114',
    province: 'General Carrera',
    cityId: '11402',
    city: 'Río Ibáñez',
  },
  {
    regionId: '12',
    region: 'Magallanes y de la Antártica Chilena',
    provinceId: '121',
    province: 'Magallanes',
    cityId: '12101',
    city: 'Punta Arenas',
  },
  {
    regionId: '12',
    region: 'Magallanes y de la Antártica Chilena',
    provinceId: '121',
    province: 'Magallanes',
    cityId: '12102',
    city: 'Laguna Blanca',
  },
  {
    regionId: '12',
    region: 'Magallanes y de la Antártica Chilena',
    provinceId: '121',
    province: 'Magallanes',
    cityId: '12103',
    city: 'Río Verde',
  },
  {
    regionId: '12',
    region: 'Magallanes y de la Antártica Chilena',
    provinceId: '121',
    province: 'Magallanes',
    cityId: '12104',
    city: 'San Gregorio',
  },
  {
    regionId: '12',
    region: 'Magallanes y de la Antártica Chilena',
    provinceId: '122',
    province: 'Antártica Chilena',
    cityId: '12201',
    city: 'Cabo de Hornos',
  },
  {
    regionId: '12',
    region: 'Magallanes y de la Antártica Chilena',
    provinceId: '122',
    province: 'Antártica Chilena',
    cityId: '12202',
    city: 'Antártica',
  },
  {
    regionId: '12',
    region: 'Magallanes y de la Antártica Chilena',
    provinceId: '123',
    province: 'Tierra del Fuego',
    cityId: '12301',
    city: 'Porvenir',
  },
  {
    regionId: '12',
    region: 'Magallanes y de la Antártica Chilena',
    provinceId: '123',
    province: 'Tierra del Fuego',
    cityId: '12302',
    city: 'Primavera',
  },
  {
    regionId: '12',
    region: 'Magallanes y de la Antártica Chilena',
    provinceId: '123',
    province: 'Tierra del Fuego',
    cityId: '12303',
    city: 'Timaukel',
  },
  {
    regionId: '12',
    region: 'Magallanes y de la Antártica Chilena',
    provinceId: '124',
    province: 'Última Esperanza',
    cityId: '12401',
    city: 'Natales',
  },
  {
    regionId: '12',
    region: 'Magallanes y de la Antártica Chilena',
    provinceId: '124',
    province: 'Última Esperanza',
    cityId: '12402',
    city: 'Torres del Paine',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '131',
    province: 'Santiago',
    cityId: '13101',
    city: 'Santiago',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '131',
    province: 'Santiago',
    cityId: '13102',
    city: 'Cerrillos',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '131',
    province: 'Santiago',
    cityId: '13103',
    city: 'Cerro Navia',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '131',
    province: 'Santiago',
    cityId: '13104',
    city: 'Conchalí',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '131',
    province: 'Santiago',
    cityId: '13105',
    city: 'El Bosque',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '131',
    province: 'Santiago',
    cityId: '13106',
    city: 'Estación Central',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '131',
    province: 'Santiago',
    cityId: '13107',
    city: 'Huechuraba',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '131',
    province: 'Santiago',
    cityId: '13108',
    city: 'Independencia',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '131',
    province: 'Santiago',
    cityId: '13109',
    city: 'La Cisterna',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '131',
    province: 'Santiago',
    cityId: '13110',
    city: 'La Florida',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '131',
    province: 'Santiago',
    cityId: '13111',
    city: 'La Granja',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '131',
    province: 'Santiago',
    cityId: '13112',
    city: 'La Pintana',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '131',
    province: 'Santiago',
    cityId: '13113',
    city: 'La Reina',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '131',
    province: 'Santiago',
    cityId: '13114',
    city: 'Las Condes',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '131',
    province: 'Santiago',
    cityId: '13115',
    city: 'Lo Barnechea',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '131',
    province: 'Santiago',
    cityId: '13116',
    city: 'Lo Espejo',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '131',
    province: 'Santiago',
    cityId: '13117',
    city: 'Lo Prado',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '131',
    province: 'Santiago',
    cityId: '13118',
    city: 'Macul',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '131',
    province: 'Santiago',
    cityId: '13119',
    city: 'Maipú',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '131',
    province: 'Santiago',
    cityId: '13120',
    city: 'Ñuñoa',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '131',
    province: 'Santiago',
    cityId: '13121',
    city: 'Pedro Aguirre Cerda',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '131',
    province: 'Santiago',
    cityId: '13122',
    city: 'Peñalolén',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '131',
    province: 'Santiago',
    cityId: '13123',
    city: 'Providencia',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '131',
    province: 'Santiago',
    cityId: '13124',
    city: 'Pudahuel',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '131',
    province: 'Santiago',
    cityId: '13125',
    city: 'Quilicura',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '131',
    province: 'Santiago',
    cityId: '13126',
    city: 'Quinta Normal',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '131',
    province: 'Santiago',
    cityId: '13127',
    city: 'Recoleta',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '131',
    province: 'Santiago',
    cityId: '13128',
    city: 'Renca',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '131',
    province: 'Santiago',
    cityId: '13129',
    city: 'San Joaquín',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '131',
    province: 'Santiago',
    cityId: '13130',
    city: 'San Miguel',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '131',
    province: 'Santiago',
    cityId: '13131',
    city: 'San Ramón',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '131',
    province: 'Santiago',
    cityId: '13132',
    city: 'Vitacura',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '132',
    province: 'Cordillera',
    cityId: '13201',
    city: 'Puente Alto',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '132',
    province: 'Cordillera',
    cityId: '13202',
    city: 'Pirque',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '132',
    province: 'Cordillera',
    cityId: '13203',
    city: 'San José de Maipo',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '133',
    province: 'Chacabuco',
    cityId: '13301',
    city: 'Colina',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '133',
    province: 'Chacabuco',
    cityId: '13302',
    city: 'Lampa',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '133',
    province: 'Chacabuco',
    cityId: '13303',
    city: 'Tiltil',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '134',
    province: 'Maipo',
    cityId: '13401',
    city: 'San Bernardo',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '134',
    province: 'Maipo',
    cityId: '13402',
    city: 'Buin',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '134',
    province: 'Maipo',
    cityId: '13403',
    city: 'Calera de Tango',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '134',
    province: 'Maipo',
    cityId: '13404',
    city: 'Paine',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '135',
    province: 'Melipilla',
    cityId: '13501',
    city: 'Melipilla',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '135',
    province: 'Melipilla',
    cityId: '13502',
    city: 'Alhué',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '135',
    province: 'Melipilla',
    cityId: '13503',
    city: 'Curacaví',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '135',
    province: 'Melipilla',
    cityId: '13504',
    city: 'María Pinto',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '135',
    province: 'Melipilla',
    cityId: '13505',
    city: 'San Pedro',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '136',
    province: 'Talagante',
    cityId: '13601',
    city: 'Talagante',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '136',
    province: 'Talagante',
    cityId: '13602',
    city: 'El Monte',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '136',
    province: 'Talagante',
    cityId: '13603',
    city: 'Isla de Maipo',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '136',
    province: 'Talagante',
    cityId: '13604',
    city: 'Padre Hurtado',
  },
  {
    regionId: '13',
    region: 'Metropolitana de Santiago',
    provinceId: '136',
    province: 'Talagante',
    cityId: '13605',
    city: 'Peñaflor',
  },
  {
    regionId: '14',
    region: 'Los Ríos',
    provinceId: '141',
    province: 'Valdivia',
    cityId: '14101',
    city: 'Valdivia',
  },
  {
    regionId: '14',
    region: 'Los Ríos',
    provinceId: '141',
    province: 'Valdivia',
    cityId: '14102',
    city: 'Corral',
  },
  {
    regionId: '14',
    region: 'Los Ríos',
    provinceId: '141',
    province: 'Valdivia',
    cityId: '14103',
    city: 'Lanco',
  },
  {
    regionId: '14',
    region: 'Los Ríos',
    provinceId: '141',
    province: 'Valdivia',
    cityId: '14104',
    city: 'Los Lagos',
  },
  {
    regionId: '14',
    region: 'Los Ríos',
    provinceId: '141',
    province: 'Valdivia',
    cityId: '14105',
    city: 'Máfil',
  },
  {
    regionId: '14',
    region: 'Los Ríos',
    provinceId: '141',
    province: 'Valdivia',
    cityId: '14106',
    city: 'Mariquina',
  },
  {
    regionId: '14',
    region: 'Los Ríos',
    provinceId: '141',
    province: 'Valdivia',
    cityId: '14107',
    city: 'Paillaco',
  },
  {
    regionId: '14',
    region: 'Los Ríos',
    provinceId: '141',
    province: 'Valdivia',
    cityId: '14108',
    city: 'Panguipulli',
  },
  {
    regionId: '14',
    region: 'Los Ríos',
    provinceId: '142',
    province: 'Ranco',
    cityId: '14201',
    city: 'La Unión',
  },
  {
    regionId: '14',
    region: 'Los Ríos',
    provinceId: '142',
    province: 'Ranco',
    cityId: '14202',
    city: 'Futrono',
  },
  {
    regionId: '14',
    region: 'Los Ríos',
    provinceId: '142',
    province: 'Ranco',
    cityId: '14203',
    city: 'Lago Ranco',
  },
  {
    regionId: '14',
    region: 'Los Ríos',
    provinceId: '142',
    province: 'Ranco',
    cityId: '14204',
    city: 'Río Bueno',
  },
  {
    regionId: '15',
    region: 'Arica y Parinacota',
    provinceId: '151',
    province: 'Arica',
    cityId: '15101',
    city: 'Arica',
  },
  {
    regionId: '15',
    region: 'Arica y Parinacota',
    provinceId: '151',
    province: 'Arica',
    cityId: '15102',
    city: 'Camarones',
  },
  {
    regionId: '15',
    region: 'Arica y Parinacota',
    provinceId: '152',
    province: 'Parinacota',
    cityId: '15201',
    city: 'Putre',
  },
  {
    regionId: '15',
    region: 'Arica y Parinacota',
    provinceId: '152',
    province: 'Parinacota',
    cityId: '15202',
    city: 'General Lagos',
  },
  {
    regionId: '16',
    region: 'Ñuble',
    provinceId: '161',
    province: 'Diguillín',
    cityId: '16101',
    city: 'Chillán',
  },
  {
    regionId: '16',
    region: 'Ñuble',
    provinceId: '161',
    province: 'Diguillín',
    cityId: '16102',
    city: 'Bulnes',
  },
  {
    regionId: '16',
    region: 'Ñuble',
    provinceId: '161',
    province: 'Diguillín',
    cityId: '16103',
    city: 'Chillán Viejo',
  },
  {
    regionId: '16',
    region: 'Ñuble',
    provinceId: '161',
    province: 'Diguillín',
    cityId: '16104',
    city: 'El Carmen',
  },
  {
    regionId: '16',
    region: 'Ñuble',
    provinceId: '161',
    province: 'Diguillín',
    cityId: '16105',
    city: 'Pemuco',
  },
  {
    regionId: '16',
    region: 'Ñuble',
    provinceId: '161',
    province: 'Diguillín',
    cityId: '16106',
    city: 'Pinto',
  },
  {
    regionId: '16',
    region: 'Ñuble',
    provinceId: '161',
    province: 'Diguillín',
    cityId: '16107',
    city: 'Quillón',
  },
  {
    regionId: '16',
    region: 'Ñuble',
    provinceId: '161',
    province: 'Diguillín',
    cityId: '16108',
    city: 'San Ignacio',
  },
  {
    regionId: '16',
    region: 'Ñuble',
    provinceId: '161',
    province: 'Diguillín',
    cityId: '16109',
    city: 'Yungay',
  },
  {
    regionId: '16',
    region: 'Ñuble',
    provinceId: '162',
    province: 'Itata',
    cityId: '16201',
    city: 'Quirihue',
  },
  {
    regionId: '16',
    region: 'Ñuble',
    provinceId: '162',
    province: 'Itata',
    cityId: '16202',
    city: 'Cobquecura',
  },
  {
    regionId: '16',
    region: 'Ñuble',
    provinceId: '162',
    province: 'Itata',
    cityId: '16203',
    city: 'Coelemu',
  },
  {
    regionId: '16',
    region: 'Ñuble',
    provinceId: '162',
    province: 'Itata',
    cityId: '16204',
    city: 'Ninhue',
  },
  {
    regionId: '16',
    region: 'Ñuble',
    provinceId: '162',
    province: 'Itata',
    cityId: '16205',
    city: 'Portezuelo',
  },
  {
    regionId: '16',
    region: 'Ñuble',
    provinceId: '162',
    province: 'Itata',
    cityId: '16206',
    city: 'Ranquil',
  },
  {
    regionId: '16',
    region: 'Ñuble',
    provinceId: '162',
    province: 'Itata',
    cityId: '16207',
    city: 'Treguaco',
  },
  {
    regionId: '16',
    region: 'Ñuble',
    provinceId: '163',
    province: 'Punilla',
    cityId: '16301',
    city: 'San Carlos',
  },
  {
    regionId: '16',
    region: 'Ñuble',
    provinceId: '163',
    province: 'Punilla',
    cityId: '16302',
    city: 'Coihueco',
  },
  {
    regionId: '16',
    region: 'Ñuble',
    provinceId: '163',
    province: 'Punilla',
    cityId: '16303',
    city: 'Ñiquén',
  },
  {
    regionId: '16',
    region: 'Ñuble',
    provinceId: '163',
    province: 'Punilla',
    cityId: '16304',
    city: 'San Fabián',
  },
  {
    regionId: '16',
    region: 'Ñuble',
    provinceId: '163',
    province: 'Punilla',
    cityId: '16305',
    city: 'San Nicolás',
  },
];
